//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum ConvertRuleState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
	}
	
	/// <summary>
	/// Defines the settings for automatic record creation.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("convertrule")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class ConvertRule : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string AllowUnknownSender = "allowunknownsender";
			public const string ChannelPropertyGroupId = "channelpropertygroupid";
			public const string CheckActiveEntitlement = "checkactiveentitlement";
			public const string CheckBlockedSocialProfile = "checkblockedsocialprofile";
			public const string CheckDirectMessages = "checkdirectmessages";
			public const string CheckIfResolved = "checkifresolved";
			public const string ComponentState = "componentstate";
			public const string ConvertRuleId = "convertruleid";
			public const string Id = "convertruleid";
			public const string ConvertRuleIdUnique = "convertruleidunique";
			public const string ConvertRuleType = "convertruletype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Description = "description";
			public const string ExchangeRate = "exchangerate";
			public const string IsManaged = "ismanaged";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string QueueId = "queueid";
			public const string RecordVersion = "recordversion";
			public const string ResolvedSince = "resolvedsince";
			public const string ResponseTemplateId = "responsetemplateid";
			public const string SendAutomaticResponse = "sendautomaticresponse";
			public const string SenderResolutionOption = "senderresolutionoption";
			public const string SolutionId = "solutionid";
			public const string SourceChannelTypeCode = "sourcechanneltypecode";
			public const string SourceTypeCode = "sourcetypecode";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string VersionNumber = "versionnumber";
			public const string WorkflowId = "workflowid";
			public const string business_unit_convertrule = "business_unit_convertrule";
			public const string convertrule_queue = "convertrule_queue";
			public const string emailtemplate_convertrule = "emailtemplate_convertrule";
			public const string lk_convertrule_createdby = "lk_convertrule_createdby";
			public const string lk_ConvertRule_createdonbehalfby = "lk_ConvertRule_createdonbehalfby";
			public const string lk_ConvertRule_modifiedby = "lk_ConvertRule_modifiedby";
			public const string lk_ConvertRule_modifiedonbehalfby = "lk_ConvertRule_modifiedonbehalfby";
			public const string team_convertrule = "team_convertrule";
			public const string TransactionCurrency_ConvertRule = "TransactionCurrency_ConvertRule";
			public const string user_convertrule = "user_convertrule";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ConvertRule() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "convertrule";
		
		public const string EntitySchemaName = "ConvertRule";
		
		public const string PrimaryIdAttribute = "convertruleid";
		
		public const string PrimaryNameAttribute = "name";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Choose whether items from unknown senders should be converted to records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowunknownsender")]
		public System.Nullable<bool> AllowUnknownSender
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("allowunknownsender");
			}
			set
			{
				this.OnPropertyChanging("AllowUnknownSender");
				this.SetAttributeValue("allowunknownsender", value);
				this.OnPropertyChanged("AllowUnknownSender");
			}
		}
		
		/// <summary>
		/// channel property group associated with the convert rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("channelpropertygroupid")]
		public Microsoft.Xrm.Sdk.EntityReference ChannelPropertyGroupId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("channelpropertygroupid");
			}
			set
			{
				this.OnPropertyChanging("ChannelPropertyGroupId");
				this.SetAttributeValue("channelpropertygroupid", value);
				this.OnPropertyChanged("ChannelPropertyGroupId");
			}
		}
		
		/// <summary>
		/// Choose whether cases should be created for customers with active entitlements.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkactiveentitlement")]
		public System.Nullable<bool> CheckActiveEntitlement
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("checkactiveentitlement");
			}
			set
			{
				this.OnPropertyChanging("CheckActiveEntitlement");
				this.SetAttributeValue("checkactiveentitlement", value);
				this.OnPropertyChanged("CheckActiveEntitlement");
			}
		}
		
		/// <summary>
		/// Information whether record needs to be created for black listed social profiles.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkblockedsocialprofile")]
		public System.Nullable<bool> CheckBlockedSocialProfile
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("checkblockedsocialprofile");
			}
			set
			{
				this.OnPropertyChanging("CheckBlockedSocialProfile");
				this.SetAttributeValue("checkblockedsocialprofile", value);
				this.OnPropertyChanged("CheckBlockedSocialProfile");
			}
		}
		
		/// <summary>
		/// Information whether record needs to be created for direct messages.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkdirectmessages")]
		public System.Nullable<bool> CheckDirectMessages
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("checkdirectmessages");
			}
			set
			{
				this.OnPropertyChanging("CheckDirectMessages");
				this.SetAttributeValue("checkdirectmessages", value);
				this.OnPropertyChanged("CheckDirectMessages");
			}
		}
		
		/// <summary>
		/// Choose whether an item related to a resolved case should be converted to a case.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkifresolved")]
		public System.Nullable<bool> CheckIfResolved
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("checkifresolved");
			}
			set
			{
				this.OnPropertyChanging("CheckIfResolved");
				this.SetAttributeValue("checkifresolved", value);
				this.OnPropertyChanged("CheckIfResolved");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public Microsoft.Xrm.Sdk.OptionSetValue ComponentState
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("componentstate");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual ComponentState? ComponentStateEnum
		{
			get
			{
				return ((ComponentState?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("convertruleid")]
		public System.Nullable<System.Guid> ConvertRuleId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("convertruleid");
			}
			set
			{
				this.OnPropertyChanging("ConvertRuleId");
				this.SetAttributeValue("convertruleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ConvertRuleId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("convertruleid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ConvertRuleId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("convertruleidunique")]
		public System.Nullable<System.Guid> ConvertRuleIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("convertruleidunique");
			}
		}
		
		/// <summary>
		/// Choose whether an ARC rule is modern or legacy.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("convertruletype")]
		public System.Nullable<bool> ConvertRuleType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("convertruletype");
			}
			set
			{
				this.OnPropertyChanging("ConvertRuleType");
				this.SetAttributeValue("convertruletype", value);
				this.OnPropertyChanged("ConvertRuleType");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Type additional information to describe the rule for creating records automatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the queue with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Type a title or name of the queue for which the setting is defined.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Shows the business unit that the convert rule owner belongs to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Choose the queue that the rule is assigned to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public Microsoft.Xrm.Sdk.EntityReference QueueId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("queueid");
			}
			set
			{
				this.OnPropertyChanging("QueueId");
				this.SetAttributeValue("queueid", value);
				this.OnPropertyChanged("QueueId");
			}
		}
		
		/// <summary>
		/// Record Version
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("recordversion")]
		public string RecordVersion
		{
			get
			{
				return this.GetAttributeValue<string>("recordversion");
			}
		}
		
		/// <summary>
		/// If you want to create a new case for an item associated with a resolved case, type how long a case must remain resolved before a new case is created for the associated item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvedsince")]
		public System.Nullable<int> ResolvedSince
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("resolvedsince");
			}
			set
			{
				this.OnPropertyChanging("ResolvedSince");
				this.SetAttributeValue("resolvedsince", value);
				this.OnPropertyChanged("ResolvedSince");
			}
		}
		
		/// <summary>
		/// Choose the email template to use to create an automatic response to the customer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responsetemplateid")]
		public Microsoft.Xrm.Sdk.EntityReference ResponseTemplateId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("responsetemplateid");
			}
			set
			{
				this.OnPropertyChanging("ResponseTemplateId");
				this.SetAttributeValue("responsetemplateid", value);
				this.OnPropertyChanged("ResponseTemplateId");
			}
		}
		
		/// <summary>
		/// Choose whether to send an automatic email response to the customer after a record is created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sendautomaticresponse")]
		public System.Nullable<bool> SendAutomaticResponse
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("sendautomaticresponse");
			}
			set
			{
				this.OnPropertyChanging("SendAutomaticResponse");
				this.SetAttributeValue("sendautomaticresponse", value);
				this.OnPropertyChanged("SendAutomaticResponse");
			}
		}
		
		/// <summary>
		/// Choose whether an ARC rule should resolve email sender manually or automatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("senderresolutionoption")]
		public Microsoft.Xrm.Sdk.OptionSetValue SenderResolutionOption
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("senderresolutionoption");
			}
			set
			{
				this.OnPropertyChanging("SenderResolutionOption");
				this.SetAttributeValue("senderresolutionoption", value);
				this.OnPropertyChanged("SenderResolutionOption");
			}
		}
		
		/// <summary>
		/// Choose whether an ARC rule should resolve email sender manually or automatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("senderresolutionoption")]
		public virtual ConvertRule_SenderResolutionOption? SenderResolutionOptionEnum
		{
			get
			{
				return ((ConvertRule_SenderResolutionOption?)(EntityOptionSetEnum.GetEnum(this, "senderresolutionoption")));
			}
			set
			{
				this.OnPropertyChanging("SenderResolutionOption");
				this.SetAttributeValue("senderresolutionoption", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("SenderResolutionOption");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Identifies the Dynamics 365 activity that's the source of the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sourcechanneltypecode")]
		public string SourceChannelTypeCode
		{
			get
			{
				return this.GetAttributeValue<string>("sourcechanneltypecode");
			}
			set
			{
				this.OnPropertyChanging("SourceChannelTypeCode");
				this.SetAttributeValue("sourcechanneltypecode", value);
				this.OnPropertyChanged("SourceChannelTypeCode");
			}
		}
		
		/// <summary>
		/// Source of the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sourcetypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue SourceTypeCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("sourcetypecode");
			}
			set
			{
				this.OnPropertyChanging("SourceTypeCode");
				this.SetAttributeValue("sourcetypecode", value);
				this.OnPropertyChanged("SourceTypeCode");
			}
		}
		
		/// <summary>
		/// Source of the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sourcetypecode")]
		public virtual ConvertRule_SourceTypeCode? SourceTypeCodeEnum
		{
			get
			{
				return ((ConvertRule_SourceTypeCode?)(EntityOptionSetEnum.GetEnum(this, "sourcetypecode")));
			}
			set
			{
				this.OnPropertyChanging("SourceTypeCode");
				this.SetAttributeValue("sourcetypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("SourceTypeCode");
			}
		}
		
		/// <summary>
		/// Status of the Convert Rule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Insight.Intake.ConvertRuleState> StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Insight.Intake.ConvertRuleState)(System.Enum.ToObject(typeof(Insight.Intake.ConvertRuleState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Convert Rule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Convert Rule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual ConvertRule_StatusCode? StatusCodeEnum
		{
			get
			{
				return ((ConvertRule_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Version number of the convert rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Shows the workflow for this rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
		public Microsoft.Xrm.Sdk.EntityReference WorkflowId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("workflowid");
			}
			set
			{
				this.OnPropertyChanging("WorkflowId");
				this.SetAttributeValue("workflowid", value);
				this.OnPropertyChanged("WorkflowId");
			}
		}
		
		/// <summary>
		/// 1:N ConvertRule_Annotation
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ConvertRule_Annotation")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Annotation> ConvertRule_Annotation
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Annotation>("ConvertRule_Annotation", null);
			}
			set
			{
				this.OnPropertyChanging("ConvertRule_Annotation");
				this.SetRelatedEntities<Insight.Intake.Annotation>("ConvertRule_Annotation", null, value);
				this.OnPropertyChanged("ConvertRule_Annotation");
			}
		}
		
		/// <summary>
		/// 1:N Convertrule_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Convertrule_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.AsyncOperation> Convertrule_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.AsyncOperation>("Convertrule_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("Convertrule_AsyncOperations");
				this.SetRelatedEntities<Insight.Intake.AsyncOperation>("Convertrule_AsyncOperations", null, value);
				this.OnPropertyChanged("Convertrule_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N convertrule_convertruleitem
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("convertrule_convertruleitem")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ConvertRuleItem> convertrule_convertruleitem
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ConvertRuleItem>("convertrule_convertruleitem", null);
			}
			set
			{
				this.OnPropertyChanging("convertrule_convertruleitem");
				this.SetRelatedEntities<Insight.Intake.ConvertRuleItem>("convertrule_convertruleitem", null, value);
				this.OnPropertyChanged("convertrule_convertruleitem");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_convertrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_convertrule")]
		public Insight.Intake.BusinessUnit business_unit_convertrule
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.BusinessUnit>("business_unit_convertrule", null);
			}
		}
		
		/// <summary>
		/// N:1 convertrule_queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("convertrule_queue")]
		public Insight.Intake.Queue convertrule_queue
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Queue>("convertrule_queue", null);
			}
			set
			{
				this.OnPropertyChanging("convertrule_queue");
				this.SetRelatedEntity<Insight.Intake.Queue>("convertrule_queue", null, value);
				this.OnPropertyChanged("convertrule_queue");
			}
		}
		
		/// <summary>
		/// N:1 emailtemplate_convertrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responsetemplateid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("emailtemplate_convertrule")]
		public Insight.Intake.Template emailtemplate_convertrule
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Template>("emailtemplate_convertrule", null);
			}
			set
			{
				this.OnPropertyChanging("emailtemplate_convertrule");
				this.SetRelatedEntity<Insight.Intake.Template>("emailtemplate_convertrule", null, value);
				this.OnPropertyChanged("emailtemplate_convertrule");
			}
		}
		
		/// <summary>
		/// N:1 lk_convertrule_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_convertrule_createdby")]
		public Insight.Intake.SystemUser lk_convertrule_createdby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_convertrule_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ConvertRule_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ConvertRule_createdonbehalfby")]
		public Insight.Intake.SystemUser lk_ConvertRule_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ConvertRule_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ConvertRule_createdonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ConvertRule_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_ConvertRule_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_ConvertRule_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ConvertRule_modifiedby")]
		public Insight.Intake.SystemUser lk_ConvertRule_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ConvertRule_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ConvertRule_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ConvertRule_modifiedonbehalfby")]
		public Insight.Intake.SystemUser lk_ConvertRule_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ConvertRule_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ConvertRule_modifiedonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ConvertRule_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_ConvertRule_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 team_convertrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_convertrule")]
		public Insight.Intake.Team team_convertrule
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Team>("team_convertrule", null);
			}
			set
			{
				this.OnPropertyChanging("team_convertrule");
				this.SetRelatedEntity<Insight.Intake.Team>("team_convertrule", null, value);
				this.OnPropertyChanged("team_convertrule");
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_ConvertRule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_ConvertRule")]
		public Insight.Intake.TransactionCurrency TransactionCurrency_ConvertRule
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.TransactionCurrency>("TransactionCurrency_ConvertRule", null);
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrency_ConvertRule");
				this.SetRelatedEntity<Insight.Intake.TransactionCurrency>("TransactionCurrency_ConvertRule", null, value);
				this.OnPropertyChanged("TransactionCurrency_ConvertRule");
			}
		}
		
		/// <summary>
		/// N:1 user_convertrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_convertrule")]
		public Insight.Intake.SystemUser user_convertrule
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("user_convertrule", null);
			}
			set
			{
				this.OnPropertyChanging("user_convertrule");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("user_convertrule", null, value);
				this.OnPropertyChanged("user_convertrule");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public ConvertRule(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["convertruleid"] = base.Id;
                        break;
                    case "convertruleid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}