//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum ipg_dxcodeState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Collection of diagnostic codes.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ipg_dxcode")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class ipg_dxcode : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ipg_Active = "ipg_active";
			public const string ipg_bodyregion = "ipg_bodyregion";
			public const string ipg_Description = "ipg_description";
			public const string ipg_DxCode = "ipg_dxcode";
			public const string ipg_dxcodeId = "ipg_dxcodeid";
			public const string Id = "ipg_dxcodeid";
			public const string ipg_dxname = "ipg_dxname";
			public const string ipg_EffectiveDate = "ipg_effectivedate";
			public const string ipg_ExpirationDate = "ipg_expirationdate";
			public const string ipg_externalid = "ipg_externalid";
			public const string ipg_gender = "ipg_gender";
			public const string ipg_ICDVersion = "ipg_icdversion";
			public const string ipg_name = "ipg_name";
			public const string ipg_TodaysDate = "ipg_todaysdate";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lk_ipg_dxcode_createdby = "lk_ipg_dxcode_createdby";
			public const string lk_ipg_dxcode_createdonbehalfby = "lk_ipg_dxcode_createdonbehalfby";
			public const string lk_ipg_dxcode_modifiedby = "lk_ipg_dxcode_modifiedby";
			public const string lk_ipg_dxcode_modifiedonbehalfby = "lk_ipg_dxcode_modifiedonbehalfby";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ipg_dxcode() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ipg_dxcode";
		
		public const string EntitySchemaName = "ipg_dxcode";
		
		public const string PrimaryIdAttribute = "ipg_dxcodeid";
		
		public const string PrimaryNameAttribute = "ipg_name";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Represents if DX Code is active or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_active")]
		public System.Nullable<bool> ipg_Active
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_active");
			}
			set
			{
				this.OnPropertyChanging("ipg_Active");
				this.SetAttributeValue("ipg_active", value);
				this.OnPropertyChanged("ipg_Active");
			}
		}
		
		/// <summary>
		/// The body region for this DxCode
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_bodyregion")]
		public Microsoft.Xrm.Sdk.OptionSetValueCollection ipg_bodyregion
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>("ipg_bodyregion");
			}
			set
			{
				this.OnPropertyChanging("ipg_bodyregion");
				this.SetAttributeValue("ipg_bodyregion", value);
				this.OnPropertyChanged("ipg_bodyregion");
			}
		}
		
		/// <summary>
		/// The body region for this DxCode
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_bodyregion")]
		public virtual System.Collections.Generic.IEnumerable<ipg_BodyRegions> ipg_bodyregionEnum
		{
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<ipg_BodyRegions>(this, "ipg_bodyregion");
			}
			set
			{
				this.OnPropertyChanging("ipg_bodyregion");
				this.SetAttributeValue("ipg_bodyregion", EntityOptionSetEnum.GetMultiEnum(this, "ipg_bodyregion", value));
				this.OnPropertyChanged("ipg_bodyregion");
			}
		}
		
		/// <summary>
		/// Description for Dx Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_description")]
		public string ipg_Description
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_description");
			}
			set
			{
				this.OnPropertyChanging("ipg_Description");
				this.SetAttributeValue("ipg_description", value);
				this.OnPropertyChanged("ipg_Description");
			}
		}
		
		/// <summary>
		/// Diagnosis code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dxcode")]
		public string ipg_DxCode
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_dxcode");
			}
			set
			{
				this.OnPropertyChanging("ipg_DxCode");
				this.SetAttributeValue("ipg_dxcode", value);
				this.OnPropertyChanged("ipg_DxCode");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dxcodeid")]
		public System.Nullable<System.Guid> ipg_dxcodeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ipg_dxcodeid");
			}
			set
			{
				this.OnPropertyChanging("ipg_dxcodeId");
				this.SetAttributeValue("ipg_dxcodeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ipg_dxcodeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dxcodeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ipg_dxcodeId = value;
			}
		}
		
		/// <summary>
		/// The name of the dxcode
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dxname")]
		public string ipg_dxname
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_dxname");
			}
			set
			{
				this.OnPropertyChanging("ipg_dxname");
				this.SetAttributeValue("ipg_dxname", value);
				this.OnPropertyChanged("ipg_dxname");
			}
		}
		
		/// <summary>
		/// Start date the dx code can be used
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_effectivedate")]
		public System.Nullable<System.DateTime> ipg_EffectiveDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_effectivedate");
			}
			set
			{
				this.OnPropertyChanging("ipg_EffectiveDate");
				this.SetAttributeValue("ipg_effectivedate", value);
				this.OnPropertyChanged("ipg_EffectiveDate");
			}
		}
		
		/// <summary>
		/// Date the dx code is no longer be used.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_expirationdate")]
		public System.Nullable<System.DateTime> ipg_ExpirationDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_expirationdate");
			}
			set
			{
				this.OnPropertyChanging("ipg_ExpirationDate");
				this.SetAttributeValue("ipg_expirationdate", value);
				this.OnPropertyChanged("ipg_ExpirationDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_externalid")]
		public string ipg_externalid
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_externalid");
			}
			set
			{
				this.OnPropertyChanging("ipg_externalid");
				this.SetAttributeValue("ipg_externalid", value);
				this.OnPropertyChanged("ipg_externalid");
			}
		}
		
		/// <summary>
		/// Gender information for the diagnosis
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_gender")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_gender
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_gender");
			}
			set
			{
				this.OnPropertyChanging("ipg_gender");
				this.SetAttributeValue("ipg_gender", value);
				this.OnPropertyChanged("ipg_gender");
			}
		}
		
		/// <summary>
		/// Gender information for the diagnosis
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_gender")]
		public virtual ipg_Gender? ipg_genderEnum
		{
			get
			{
				return ((ipg_Gender?)(EntityOptionSetEnum.GetEnum(this, "ipg_gender")));
			}
			set
			{
				this.OnPropertyChanging("ipg_gender");
				this.SetAttributeValue("ipg_gender", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_gender");
			}
		}
		
		/// <summary>
		/// Used as a claim field (both CMS and UB04)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_icdversion")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_ICDVersion
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_icdversion");
			}
			set
			{
				this.OnPropertyChanging("ipg_ICDVersion");
				this.SetAttributeValue("ipg_icdversion", value);
				this.OnPropertyChanged("ipg_ICDVersion");
			}
		}
		
		/// <summary>
		/// Used as a claim field (both CMS and UB04)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_icdversion")]
		public virtual ipg_ICDVersion? ipg_ICDVersionEnum
		{
			get
			{
				return ((ipg_ICDVersion?)(EntityOptionSetEnum.GetEnum(this, "ipg_icdversion")));
			}
			set
			{
				this.OnPropertyChanging("ipg_ICDVersion");
				this.SetAttributeValue("ipg_icdversion", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_ICDVersion");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_name")]
		public string ipg_name
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_name");
			}
			set
			{
				this.OnPropertyChanging("ipg_name");
				this.SetAttributeValue("ipg_name", value);
				this.OnPropertyChanged("ipg_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_todaysdate")]
		public System.Nullable<System.DateTime> ipg_TodaysDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_todaysdate");
			}
			set
			{
				this.OnPropertyChanging("ipg_TodaysDate");
				this.SetAttributeValue("ipg_todaysdate", value);
				this.OnPropertyChanged("ipg_TodaysDate");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Status of the Dx Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Insight.Intake.ipg_dxcodeState> StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Insight.Intake.ipg_dxcodeState)(System.Enum.ToObject(typeof(Insight.Intake.ipg_dxcodeState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Dx Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Dx Code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual ipg_dxcode_StatusCode? StatusCodeEnum
		{
			get
			{
				return ((ipg_dxcode_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N ipg_dxcode_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_dxcode_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.AsyncOperation> ipg_dxcode_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.AsyncOperation>("ipg_dxcode_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_dxcode_AsyncOperations");
				this.SetRelatedEntities<Insight.Intake.AsyncOperation>("ipg_dxcode_AsyncOperations", null, value);
				this.OnPropertyChanged("ipg_dxcode_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N ipg_dxcode_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_dxcode_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> ipg_dxcode_DuplicateBaseRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_dxcode_DuplicateBaseRecord", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_dxcode_DuplicateBaseRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_dxcode_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("ipg_dxcode_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N ipg_dxcode_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_dxcode_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> ipg_dxcode_DuplicateMatchingRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_dxcode_DuplicateMatchingRecord", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_dxcode_DuplicateMatchingRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_dxcode_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("ipg_dxcode_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N ipg_dxcode_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_dxcode_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.PrincipalObjectAttributeAccess> ipg_dxcode_PrincipalObjectAttributeAccesses
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("ipg_dxcode_PrincipalObjectAttributeAccesses", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_dxcode_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("ipg_dxcode_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("ipg_dxcode_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_incident_DxCodeId1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_incident_DxCodeId1")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_ipg_dxcode_incident_DxCodeId1
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId1", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_incident_DxCodeId1");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId1", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_incident_DxCodeId1");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_incident_DxCodeId2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_incident_DxCodeId2")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_ipg_dxcode_incident_DxCodeId2
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId2", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_incident_DxCodeId2");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId2", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_incident_DxCodeId2");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_incident_DxCodeId3
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_incident_DxCodeId3")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_ipg_dxcode_incident_DxCodeId3
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId3", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_incident_DxCodeId3");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId3", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_incident_DxCodeId3");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_incident_DxCodeId4
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_incident_DxCodeId4")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_ipg_dxcode_incident_DxCodeId4
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId4", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_incident_DxCodeId4");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId4", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_incident_DxCodeId4");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_incident_DxCodeId5
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_incident_DxCodeId5")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_ipg_dxcode_incident_DxCodeId5
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId5", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_incident_DxCodeId5");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId5", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_incident_DxCodeId5");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_incident_DxCodeId6
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_incident_DxCodeId6")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_ipg_dxcode_incident_DxCodeId6
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId6", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_incident_DxCodeId6");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_ipg_dxcode_incident_DxCodeId6", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_incident_DxCodeId6");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_dxcptrelationship> ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_dxcptrelationship>("ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId");
				this.SetRelatedEntities<Insight.Intake.ipg_dxcptrelationship>("ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_ipg_dxcptrelationship_DxCodeId");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_ipg_referral_DxCodeId1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_ipg_referral_DxCodeId1")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_referral> ipg_ipg_dxcode_ipg_referral_DxCodeId1
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_referral>("ipg_ipg_dxcode_ipg_referral_DxCodeId1", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_ipg_referral_DxCodeId1");
				this.SetRelatedEntities<Insight.Intake.ipg_referral>("ipg_ipg_dxcode_ipg_referral_DxCodeId1", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_ipg_referral_DxCodeId1");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_ipg_referral_DxCodeId2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_ipg_referral_DxCodeId2")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_referral> ipg_ipg_dxcode_ipg_referral_DxCodeId2
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_referral>("ipg_ipg_dxcode_ipg_referral_DxCodeId2", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_ipg_referral_DxCodeId2");
				this.SetRelatedEntities<Insight.Intake.ipg_referral>("ipg_ipg_dxcode_ipg_referral_DxCodeId2", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_ipg_referral_DxCodeId2");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_ipg_referral_DxCodeId3
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_ipg_referral_DxCodeId3")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_referral> ipg_ipg_dxcode_ipg_referral_DxCodeId3
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_referral>("ipg_ipg_dxcode_ipg_referral_DxCodeId3", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_ipg_referral_DxCodeId3");
				this.SetRelatedEntities<Insight.Intake.ipg_referral>("ipg_ipg_dxcode_ipg_referral_DxCodeId3", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_ipg_referral_DxCodeId3");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_unsupporteddxcode> ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_unsupporteddxcode>("ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId");
				this.SetRelatedEntities<Insight.Intake.ipg_unsupporteddxcode>("ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId", null, value);
				this.OnPropertyChanged("ipg_ipg_dxcode_ipg_unsupporteddxcode_DxCodeId");
			}
		}
		
		/// <summary>
		/// N:N ipg_incident_ipg_dxcode
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_incident_ipg_dxcode")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> ipg_incident_ipg_dxcode
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("ipg_incident_ipg_dxcode", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_incident_ipg_dxcode");
				this.SetRelatedEntities<Insight.Intake.Incident>("ipg_incident_ipg_dxcode", null, value);
				this.OnPropertyChanged("ipg_incident_ipg_dxcode");
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_dxcode_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_dxcode_createdby")]
		public Insight.Intake.SystemUser lk_ipg_dxcode_createdby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_dxcode_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_dxcode_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_dxcode_createdonbehalfby")]
		public Insight.Intake.SystemUser lk_ipg_dxcode_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_dxcode_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ipg_dxcode_createdonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_dxcode_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_ipg_dxcode_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_dxcode_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_dxcode_modifiedby")]
		public Insight.Intake.SystemUser lk_ipg_dxcode_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_dxcode_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_dxcode_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_dxcode_modifiedonbehalfby")]
		public Insight.Intake.SystemUser lk_ipg_dxcode_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_dxcode_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ipg_dxcode_modifiedonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_dxcode_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_ipg_dxcode_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public ipg_dxcode(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ipg_dxcodeid"] = base.Id;
                        break;
                    case "ipg_dxcodeid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}