//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum ipg_medrecordsconditionsState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ipg_medrecordsconditions")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class ipg_medrecordsconditions : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ipg_active = "ipg_active";
			public const string ipg_carrierid = "ipg_carrierid";
			public const string ipg_cptcodeid = "ipg_cptcodeid";
			public const string ipg_hcpcsid = "ipg_hcpcsid";
			public const string ipg_medrecordsconditionsId = "ipg_medrecordsconditionsid";
			public const string Id = "ipg_medrecordsconditionsid";
			public const string ipg_memberidstartswith = "ipg_memberidstartswith";
			public const string ipg_name = "ipg_name";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_ipg_medrecordsconditions = "business_unit_ipg_medrecordsconditions";
			public const string ipg_account_ipg_medrecordsconditions = "ipg_account_ipg_medrecordsconditions";
			public const string ipg_ipg_cptcode_ipg_medrecordsconditions = "ipg_ipg_cptcode_ipg_medrecordsconditions";
			public const string ipg_ipg_masterhcpcs_ipg_medrecordsconditions = "ipg_ipg_masterhcpcs_ipg_medrecordsconditions";
			public const string lk_ipg_medrecordsconditions_createdby = "lk_ipg_medrecordsconditions_createdby";
			public const string lk_ipg_medrecordsconditions_createdonbehalfby = "lk_ipg_medrecordsconditions_createdonbehalfby";
			public const string lk_ipg_medrecordsconditions_modifiedby = "lk_ipg_medrecordsconditions_modifiedby";
			public const string lk_ipg_medrecordsconditions_modifiedonbehalfby = "lk_ipg_medrecordsconditions_modifiedonbehalfby";
			public const string team_ipg_medrecordsconditions = "team_ipg_medrecordsconditions";
			public const string user_ipg_medrecordsconditions = "user_ipg_medrecordsconditions";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ipg_medrecordsconditions() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ipg_medrecordsconditions";
		
		public const string EntitySchemaName = "ipg_medrecordsconditions";
		
		public const string PrimaryIdAttribute = "ipg_medrecordsconditionsid";
		
		public const string PrimaryNameAttribute = "ipg_name";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_active")]
		public System.Nullable<bool> ipg_active
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_active");
			}
			set
			{
				this.OnPropertyChanging("ipg_active");
				this.SetAttributeValue("ipg_active", value);
				this.OnPropertyChanged("ipg_active");
			}
		}
		
		/// <summary>
		/// Unique identifier for Account associated with Med Records Conditions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_carrierid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_carrierid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_carrierid");
			}
			set
			{
				this.OnPropertyChanging("ipg_carrierid");
				this.SetAttributeValue("ipg_carrierid", value);
				this.OnPropertyChanged("ipg_carrierid");
			}
		}
		
		/// <summary>
		/// Unique identifier for CPT Code associated with Med Records Conditions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_cptcodeid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_cptcodeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_cptcodeid");
			}
			set
			{
				this.OnPropertyChanging("ipg_cptcodeid");
				this.SetAttributeValue("ipg_cptcodeid", value);
				this.OnPropertyChanged("ipg_cptcodeid");
			}
		}
		
		/// <summary>
		/// Unique identifier for Master HCPCS Code associated with Med Records Conditions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_hcpcsid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_hcpcsid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_hcpcsid");
			}
			set
			{
				this.OnPropertyChanging("ipg_hcpcsid");
				this.SetAttributeValue("ipg_hcpcsid", value);
				this.OnPropertyChanged("ipg_hcpcsid");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_medrecordsconditionsid")]
		public System.Nullable<System.Guid> ipg_medrecordsconditionsId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ipg_medrecordsconditionsid");
			}
			set
			{
				this.OnPropertyChanging("ipg_medrecordsconditionsId");
				this.SetAttributeValue("ipg_medrecordsconditionsid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ipg_medrecordsconditionsId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_medrecordsconditionsid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ipg_medrecordsconditionsId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberidstartswith")]
		public string ipg_memberidstartswith
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_memberidstartswith");
			}
			set
			{
				this.OnPropertyChanging("ipg_memberidstartswith");
				this.SetAttributeValue("ipg_memberidstartswith", value);
				this.OnPropertyChanged("ipg_memberidstartswith");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_name")]
		public string ipg_name
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_name");
			}
			set
			{
				this.OnPropertyChanging("ipg_name");
				this.SetAttributeValue("ipg_name", value);
				this.OnPropertyChanged("ipg_name");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Med Records Conditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Insight.Intake.ipg_medrecordsconditionsState> StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Insight.Intake.ipg_medrecordsconditionsState)(System.Enum.ToObject(typeof(Insight.Intake.ipg_medrecordsconditionsState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Med Records Conditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Med Records Conditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual ipg_medrecordsconditions_StatusCode? StatusCodeEnum
		{
			get
			{
				return ((ipg_medrecordsconditions_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N ipg_medrecordsconditions_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_medrecordsconditions_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.AsyncOperation> ipg_medrecordsconditions_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.AsyncOperation>("ipg_medrecordsconditions_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_medrecordsconditions_AsyncOperations");
				this.SetRelatedEntities<Insight.Intake.AsyncOperation>("ipg_medrecordsconditions_AsyncOperations", null, value);
				this.OnPropertyChanged("ipg_medrecordsconditions_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N ipg_medrecordsconditions_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_medrecordsconditions_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> ipg_medrecordsconditions_DuplicateBaseRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_medrecordsconditions_DuplicateBaseRecord", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_medrecordsconditions_DuplicateBaseRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_medrecordsconditions_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("ipg_medrecordsconditions_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N ipg_medrecordsconditions_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_medrecordsconditions_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> ipg_medrecordsconditions_DuplicateMatchingRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_medrecordsconditions_DuplicateMatchingRecord", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_medrecordsconditions_DuplicateMatchingRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_medrecordsconditions_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("ipg_medrecordsconditions_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N ipg_medrecordsconditions_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_medrecordsconditions_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.PrincipalObjectAttributeAccess> ipg_medrecordsconditions_PrincipalObjectAttributeAccesses
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("ipg_medrecordsconditions_PrincipalObjectAttributeAccesses", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_medrecordsconditions_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("ipg_medrecordsconditions_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("ipg_medrecordsconditions_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// N:N ipg_ipg_medrecordsconditions_ipg_documenttype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_medrecordsconditions_ipg_documenttype")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_documenttype> ipg_ipg_medrecordsconditions_ipg_documenttype
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_documenttype>("ipg_ipg_medrecordsconditions_ipg_documenttype", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_medrecordsconditions_ipg_documenttype");
				this.SetRelatedEntities<Insight.Intake.ipg_documenttype>("ipg_ipg_medrecordsconditions_ipg_documenttype", null, value);
				this.OnPropertyChanged("ipg_ipg_medrecordsconditions_ipg_documenttype");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_ipg_medrecordsconditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_ipg_medrecordsconditions")]
		public Insight.Intake.BusinessUnit business_unit_ipg_medrecordsconditions
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.BusinessUnit>("business_unit_ipg_medrecordsconditions", null);
			}
		}
		
		/// <summary>
		/// N:1 ipg_account_ipg_medrecordsconditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_carrierid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_account_ipg_medrecordsconditions")]
		public Insight.Intake.Account ipg_account_ipg_medrecordsconditions
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Account>("ipg_account_ipg_medrecordsconditions", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_account_ipg_medrecordsconditions");
				this.SetRelatedEntity<Insight.Intake.Account>("ipg_account_ipg_medrecordsconditions", null, value);
				this.OnPropertyChanged("ipg_account_ipg_medrecordsconditions");
			}
		}
		
		/// <summary>
		/// N:1 ipg_ipg_cptcode_ipg_medrecordsconditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_cptcodeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_cptcode_ipg_medrecordsconditions")]
		public Insight.Intake.ipg_cptcode ipg_ipg_cptcode_ipg_medrecordsconditions
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.ipg_cptcode>("ipg_ipg_cptcode_ipg_medrecordsconditions", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_cptcode_ipg_medrecordsconditions");
				this.SetRelatedEntity<Insight.Intake.ipg_cptcode>("ipg_ipg_cptcode_ipg_medrecordsconditions", null, value);
				this.OnPropertyChanged("ipg_ipg_cptcode_ipg_medrecordsconditions");
			}
		}
		
		/// <summary>
		/// N:1 ipg_ipg_masterhcpcs_ipg_medrecordsconditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_hcpcsid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_masterhcpcs_ipg_medrecordsconditions")]
		public Insight.Intake.ipg_masterhcpcs ipg_ipg_masterhcpcs_ipg_medrecordsconditions
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.ipg_masterhcpcs>("ipg_ipg_masterhcpcs_ipg_medrecordsconditions", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_masterhcpcs_ipg_medrecordsconditions");
				this.SetRelatedEntity<Insight.Intake.ipg_masterhcpcs>("ipg_ipg_masterhcpcs_ipg_medrecordsconditions", null, value);
				this.OnPropertyChanged("ipg_ipg_masterhcpcs_ipg_medrecordsconditions");
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_medrecordsconditions_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_medrecordsconditions_createdby")]
		public Insight.Intake.SystemUser lk_ipg_medrecordsconditions_createdby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_medrecordsconditions_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_medrecordsconditions_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_medrecordsconditions_createdonbehalfby")]
		public Insight.Intake.SystemUser lk_ipg_medrecordsconditions_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_medrecordsconditions_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ipg_medrecordsconditions_createdonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_medrecordsconditions_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_ipg_medrecordsconditions_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_medrecordsconditions_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_medrecordsconditions_modifiedby")]
		public Insight.Intake.SystemUser lk_ipg_medrecordsconditions_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_medrecordsconditions_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_medrecordsconditions_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_medrecordsconditions_modifiedonbehalfby")]
		public Insight.Intake.SystemUser lk_ipg_medrecordsconditions_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_medrecordsconditions_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ipg_medrecordsconditions_modifiedonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_medrecordsconditions_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_ipg_medrecordsconditions_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 team_ipg_medrecordsconditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_ipg_medrecordsconditions")]
		public Insight.Intake.Team team_ipg_medrecordsconditions
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Team>("team_ipg_medrecordsconditions", null);
			}
		}
		
		/// <summary>
		/// N:1 user_ipg_medrecordsconditions
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_ipg_medrecordsconditions")]
		public Insight.Intake.SystemUser user_ipg_medrecordsconditions
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("user_ipg_medrecordsconditions", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public ipg_medrecordsconditions(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ipg_medrecordsconditionsid"] = base.Id;
                        break;
                    case "ipg_medrecordsconditionsid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}