//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	/// <summary>
	/// Use EHRStaging entity instead of this entity.
	///Virtual entity that uses EHR Intake COSMOS DB as a DataSource  to display read only screen for staged EHR records.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ipg_ehrreview")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class ipg_ehrreview : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string ipg_Archive = "ipg_archive";
			public const string ipg_BatchId = "ipg_batchid";
			public const string ipg_DataSource = "ipg_datasource";
			public const string ipg_datasourcecode = "ipg_datasourcecode";
			public const string ipg_DateEntered = "ipg_dateentered";
			public const string ipg_ehrreviewId = "ipg_ehrreviewid";
			public const string Id = "ipg_ehrreviewid";
			public const string ipg_externalid = "ipg_externalid";
			public const string ipg_facilityid = "ipg_facilityid";
			public const string ipg_FacilityName = "ipg_facilityname";
			public const string ipg_name = "ipg_name";
			public const string ipg_Notes = "ipg_notes";
			public const string ipg_PatientFirstName = "ipg_patientfirstname";
			public const string ipg_PatientLastName = "ipg_patientlastname";
			public const string ipg_PrimaryPayer = "ipg_primarypayer";
			public const string ipg_ProcedureDescription = "ipg_proceduredescription";
			public const string ipg_processdate = "ipg_processdate";
			public const string ipg_ScheduledDos = "ipg_scheduleddos";
			public const string ipg_SecondaryPayer = "ipg_secondarypayer";
			public const string ipg_account_ipg_ehrreview_Facility = "ipg_account_ipg_ehrreview_Facility";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ipg_ehrreview() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ipg_ehrreview";
		
		public const string EntitySchemaName = "ipg_ehrreview";
		
		public const string PrimaryIdAttribute = "ipg_ehrreviewid";
		
		public const string PrimaryNameAttribute = "ipg_name";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_archive")]
		public System.Nullable<bool> ipg_Archive
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_archive");
			}
			set
			{
				this.OnPropertyChanging("ipg_Archive");
				this.SetAttributeValue("ipg_archive", value);
				this.OnPropertyChanged("ipg_Archive");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_batchid")]
		public string ipg_BatchId
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_batchid");
			}
			set
			{
				this.OnPropertyChanging("ipg_BatchId");
				this.SetAttributeValue("ipg_batchid", value);
				this.OnPropertyChanged("ipg_BatchId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_datasource")]
		public string ipg_DataSource
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_datasource");
			}
			set
			{
				this.OnPropertyChanging("ipg_DataSource");
				this.SetAttributeValue("ipg_datasource", value);
				this.OnPropertyChanged("ipg_DataSource");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_datasourcecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_datasourcecode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_datasourcecode");
			}
			set
			{
				this.OnPropertyChanging("ipg_datasourcecode");
				this.SetAttributeValue("ipg_datasourcecode", value);
				this.OnPropertyChanged("ipg_datasourcecode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_datasourcecode")]
		public virtual ipg_FacilityOrdersCode? ipg_datasourcecodeEnum
		{
			get
			{
				return ((ipg_FacilityOrdersCode?)(EntityOptionSetEnum.GetEnum(this, "ipg_datasourcecode")));
			}
			set
			{
				this.OnPropertyChanging("ipg_datasourcecode");
				this.SetAttributeValue("ipg_datasourcecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_datasourcecode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dateentered")]
		public System.Nullable<System.DateTime> ipg_DateEntered
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_dateentered");
			}
			set
			{
				this.OnPropertyChanging("ipg_DateEntered");
				this.SetAttributeValue("ipg_dateentered", value);
				this.OnPropertyChanged("ipg_DateEntered");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ehrreviewid")]
		public System.Nullable<System.Guid> ipg_ehrreviewId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ipg_ehrreviewid");
			}
			set
			{
				this.OnPropertyChanging("ipg_ehrreviewId");
				this.SetAttributeValue("ipg_ehrreviewid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ipg_ehrreviewId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ehrreviewid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ipg_ehrreviewId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_externalid")]
		public string ipg_externalid
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_externalid");
			}
			set
			{
				this.OnPropertyChanging("ipg_externalid");
				this.SetAttributeValue("ipg_externalid", value);
				this.OnPropertyChanged("ipg_externalid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_facilityid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_facilityid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_facilityid");
			}
			set
			{
				this.OnPropertyChanging("ipg_facilityid");
				this.SetAttributeValue("ipg_facilityid", value);
				this.OnPropertyChanged("ipg_facilityid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_facilityname")]
		public string ipg_FacilityName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_facilityname");
			}
			set
			{
				this.OnPropertyChanging("ipg_FacilityName");
				this.SetAttributeValue("ipg_facilityname", value);
				this.OnPropertyChanged("ipg_FacilityName");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_name")]
		public string ipg_name
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_name");
			}
			set
			{
				this.OnPropertyChanging("ipg_name");
				this.SetAttributeValue("ipg_name", value);
				this.OnPropertyChanged("ipg_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_notes")]
		public string ipg_Notes
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_notes");
			}
			set
			{
				this.OnPropertyChanging("ipg_Notes");
				this.SetAttributeValue("ipg_notes", value);
				this.OnPropertyChanged("ipg_Notes");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_patientfirstname")]
		public string ipg_PatientFirstName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_patientfirstname");
			}
			set
			{
				this.OnPropertyChanging("ipg_PatientFirstName");
				this.SetAttributeValue("ipg_patientfirstname", value);
				this.OnPropertyChanged("ipg_PatientFirstName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_patientlastname")]
		public string ipg_PatientLastName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_patientlastname");
			}
			set
			{
				this.OnPropertyChanging("ipg_PatientLastName");
				this.SetAttributeValue("ipg_patientlastname", value);
				this.OnPropertyChanged("ipg_PatientLastName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_primarypayer")]
		public string ipg_PrimaryPayer
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_primarypayer");
			}
			set
			{
				this.OnPropertyChanging("ipg_PrimaryPayer");
				this.SetAttributeValue("ipg_primarypayer", value);
				this.OnPropertyChanged("ipg_PrimaryPayer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_proceduredescription")]
		public string ipg_ProcedureDescription
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_proceduredescription");
			}
			set
			{
				this.OnPropertyChanging("ipg_ProcedureDescription");
				this.SetAttributeValue("ipg_proceduredescription", value);
				this.OnPropertyChanged("ipg_ProcedureDescription");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_processdate")]
		public System.Nullable<System.DateTime> ipg_processdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_processdate");
			}
			set
			{
				this.OnPropertyChanging("ipg_processdate");
				this.SetAttributeValue("ipg_processdate", value);
				this.OnPropertyChanged("ipg_processdate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_scheduleddos")]
		public string ipg_ScheduledDos
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_scheduleddos");
			}
			set
			{
				this.OnPropertyChanging("ipg_ScheduledDos");
				this.SetAttributeValue("ipg_scheduleddos", value);
				this.OnPropertyChanged("ipg_ScheduledDos");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_secondarypayer")]
		public string ipg_SecondaryPayer
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_secondarypayer");
			}
			set
			{
				this.OnPropertyChanging("ipg_SecondaryPayer");
				this.SetAttributeValue("ipg_secondarypayer", value);
				this.OnPropertyChanged("ipg_SecondaryPayer");
			}
		}
		
		/// <summary>
		/// N:1 ipg_account_ipg_ehrreview_Facility
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_facilityid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_account_ipg_ehrreview_Facility")]
		public Insight.Intake.Account ipg_account_ipg_ehrreview_Facility
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Account>("ipg_account_ipg_ehrreview_Facility", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_account_ipg_ehrreview_Facility");
				this.SetRelatedEntity<Insight.Intake.Account>("ipg_account_ipg_ehrreview_Facility", null, value);
				this.OnPropertyChanged("ipg_account_ipg_ehrreview_Facility");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public ipg_ehrreview(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ipg_ehrreviewid"] = base.Id;
                        break;
                    case "ipg_ehrreviewid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}