//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ipg_ebvinquiry")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class ipg_EBVInquiry : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string ipg_CaseId = "ipg_caseid";
			public const string ipg_CreatedAt = "ipg_createdat";
			public const string ipg_DependentDOB = "ipg_dependentdob";
			public const string ipg_DependentFirstName = "ipg_dependentfirstname";
			public const string ipg_DependentLastName = "ipg_dependentlastname";
			public const string ipg_DependentMiddleName = "ipg_dependentmiddlename";
			public const string ipg_Discriminator = "ipg_discriminator";
			public const string ipg_DOS = "ipg_dos";
			public const string ipg_EBVInquiryId = "ipg_ebvinquiryid";
			public const string Id = "ipg_ebvinquiryid";
			public const string ipg_IsUserGenerated = "ipg_isusergenerated";
			public const string ipg_MemberId = "ipg_memberid";
			public const string ipg_name = "ipg_name";
			public const string ipg_patientid = "ipg_patientid";
			public const string ipg_PayerCode = "ipg_payercode";
			public const string ipg_PayerName = "ipg_payername";
			public const string ipg_PolicyNumber = "ipg_policynumber";
			public const string ipg_ProviderName = "ipg_providername";
			public const string ipg_ProviderNpi = "ipg_providernpi";
			public const string ipg_ProviderTaxId = "ipg_providertaxid";
			public const string ipg_ReceiverId = "ipg_receiverid";
			public const string ipg_RelationToInsured = "ipg_relationtoinsured";
			public const string ipg_ResponseId = "ipg_responseid";
			public const string ipg_ResponseStatus = "ipg_responsestatus";
			public const string ipg_SenderId = "ipg_senderid";
			public const string ipg_Status = "ipg_status";
			public const string ipg_SubscriberDOB = "ipg_subscriberdob";
			public const string ipg_SubscriberFirstName = "ipg_subscriberfirstname";
			public const string ipg_SubscriberGender = "ipg_subscribergender";
			public const string ipg_SubscriberLastName = "ipg_subscriberlastname";
			public const string ipg_SubscriberMiddleName = "ipg_subscribermiddlename";
			public const string ipg_contact_ipg_ebvinquiry_patientid = "ipg_contact_ipg_ebvinquiry_patientid";
			public const string ipg_incident_ipg_ebvinquiry_CaseId = "ipg_incident_ipg_ebvinquiry_CaseId";
			public const string ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId = "ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId";
			public const string ipg_carrierid = "ipg_carrierid";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ipg_EBVInquiry() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ipg_ebvinquiry";
		
		public const string EntitySchemaName = "ipg_EBVInquiry";
		
		public const string PrimaryIdAttribute = "ipg_ebvinquiryid";
		
		public const string PrimaryNameAttribute = "ipg_name";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// The case lookup
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_caseid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_CaseId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_caseid");
			}
			set
			{
				this.OnPropertyChanging("ipg_CaseId");
				this.SetAttributeValue("ipg_caseid", value);
				this.OnPropertyChanged("ipg_CaseId");
			}
		}
		
		/// <summary>
		/// The date and time when the inquiry was created
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_createdat")]
		public System.Nullable<System.DateTime> ipg_CreatedAt
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_createdat");
			}
			set
			{
				this.OnPropertyChanging("ipg_CreatedAt");
				this.SetAttributeValue("ipg_createdat", value);
				this.OnPropertyChanged("ipg_CreatedAt");
			}
		}
		
		/// <summary>
		/// The dependent date of birth
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dependentdob")]
		public System.Nullable<System.DateTime> ipg_DependentDOB
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_dependentdob");
			}
			set
			{
				this.OnPropertyChanging("ipg_DependentDOB");
				this.SetAttributeValue("ipg_dependentdob", value);
				this.OnPropertyChanged("ipg_DependentDOB");
			}
		}
		
		/// <summary>
		/// The dependent first name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dependentfirstname")]
		public string ipg_DependentFirstName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_dependentfirstname");
			}
			set
			{
				this.OnPropertyChanging("ipg_DependentFirstName");
				this.SetAttributeValue("ipg_dependentfirstname", value);
				this.OnPropertyChanged("ipg_DependentFirstName");
			}
		}
		
		/// <summary>
		/// The dependent last name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dependentlastname")]
		public string ipg_DependentLastName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_dependentlastname");
			}
			set
			{
				this.OnPropertyChanging("ipg_DependentLastName");
				this.SetAttributeValue("ipg_dependentlastname", value);
				this.OnPropertyChanged("ipg_DependentLastName");
			}
		}
		
		/// <summary>
		/// The dependent middle name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dependentmiddlename")]
		public string ipg_DependentMiddleName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_dependentmiddlename");
			}
			set
			{
				this.OnPropertyChanging("ipg_DependentMiddleName");
				this.SetAttributeValue("ipg_dependentmiddlename", value);
				this.OnPropertyChanged("ipg_DependentMiddleName");
			}
		}
		
		/// <summary>
		/// The discriminator
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_discriminator")]
		public string ipg_Discriminator
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_discriminator");
			}
			set
			{
				this.OnPropertyChanging("ipg_Discriminator");
				this.SetAttributeValue("ipg_discriminator", value);
				this.OnPropertyChanged("ipg_Discriminator");
			}
		}
		
		/// <summary>
		/// The date of service
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dos")]
		public System.Nullable<System.DateTime> ipg_DOS
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_dos");
			}
			set
			{
				this.OnPropertyChanging("ipg_DOS");
				this.SetAttributeValue("ipg_dos", value);
				this.OnPropertyChanged("ipg_DOS");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ebvinquiryid")]
		public System.Nullable<System.Guid> ipg_EBVInquiryId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ipg_ebvinquiryid");
			}
			set
			{
				this.OnPropertyChanging("ipg_EBVInquiryId");
				this.SetAttributeValue("ipg_ebvinquiryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ipg_EBVInquiryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ebvinquiryid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ipg_EBVInquiryId = value;
			}
		}
		
		/// <summary>
		/// Whether the inquiry has been generated by the user or by the system
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_isusergenerated")]
		public System.Nullable<bool> ipg_IsUserGenerated
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_isusergenerated");
			}
			set
			{
				this.OnPropertyChanging("ipg_IsUserGenerated");
				this.SetAttributeValue("ipg_isusergenerated", value);
				this.OnPropertyChanged("ipg_IsUserGenerated");
			}
		}
		
		/// <summary>
		/// The member ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberid")]
		public string ipg_MemberId
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_memberid");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberId");
				this.SetAttributeValue("ipg_memberid", value);
				this.OnPropertyChanged("ipg_MemberId");
			}
		}
		
		/// <summary>
		/// The request ID.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_name")]
		public string ipg_name
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_name");
			}
			set
			{
				this.OnPropertyChanging("ipg_name");
				this.SetAttributeValue("ipg_name", value);
				this.OnPropertyChanged("ipg_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_patientid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_patientid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_patientid");
			}
			set
			{
				this.OnPropertyChanging("ipg_patientid");
				this.SetAttributeValue("ipg_patientid", value);
				this.OnPropertyChanged("ipg_patientid");
			}
		}
		
		/// <summary>
		/// The payer code
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_payercode")]
		public string ipg_PayerCode
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_payercode");
			}
			set
			{
				this.OnPropertyChanging("ipg_PayerCode");
				this.SetAttributeValue("ipg_payercode", value);
				this.OnPropertyChanged("ipg_PayerCode");
			}
		}
		
		/// <summary>
		/// The payer name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_payername")]
		public string ipg_PayerName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_payername");
			}
			set
			{
				this.OnPropertyChanging("ipg_PayerName");
				this.SetAttributeValue("ipg_payername", value);
				this.OnPropertyChanged("ipg_PayerName");
			}
		}
		
		/// <summary>
		/// The policy number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_policynumber")]
		public string ipg_PolicyNumber
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_policynumber");
			}
			set
			{
				this.OnPropertyChanging("ipg_PolicyNumber");
				this.SetAttributeValue("ipg_policynumber", value);
				this.OnPropertyChanged("ipg_PolicyNumber");
			}
		}
		
		/// <summary>
		/// The provider name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_providername")]
		public string ipg_ProviderName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_providername");
			}
			set
			{
				this.OnPropertyChanging("ipg_ProviderName");
				this.SetAttributeValue("ipg_providername", value);
				this.OnPropertyChanged("ipg_ProviderName");
			}
		}
		
		/// <summary>
		/// The national provider identificator of IPG
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_providernpi")]
		public string ipg_ProviderNpi
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_providernpi");
			}
			set
			{
				this.OnPropertyChanging("ipg_ProviderNpi");
				this.SetAttributeValue("ipg_providernpi", value);
				this.OnPropertyChanged("ipg_ProviderNpi");
			}
		}
		
		/// <summary>
		/// The provider tax ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_providertaxid")]
		public string ipg_ProviderTaxId
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_providertaxid");
			}
			set
			{
				this.OnPropertyChanging("ipg_ProviderTaxId");
				this.SetAttributeValue("ipg_providertaxid", value);
				this.OnPropertyChanged("ipg_ProviderTaxId");
			}
		}
		
		/// <summary>
		/// The receiver ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_receiverid")]
		public string ipg_ReceiverId
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_receiverid");
			}
			set
			{
				this.OnPropertyChanging("ipg_ReceiverId");
				this.SetAttributeValue("ipg_receiverid", value);
				this.OnPropertyChanged("ipg_ReceiverId");
			}
		}
		
		/// <summary>
		/// The relation to insured
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_relationtoinsured")]
		public string ipg_RelationToInsured
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_relationtoinsured");
			}
			set
			{
				this.OnPropertyChanging("ipg_RelationToInsured");
				this.SetAttributeValue("ipg_relationtoinsured", value);
				this.OnPropertyChanged("ipg_RelationToInsured");
			}
		}
		
		/// <summary>
		/// The response lookup
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_responseid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_ResponseId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_responseid");
			}
			set
			{
				this.OnPropertyChanging("ipg_ResponseId");
				this.SetAttributeValue("ipg_responseid", value);
				this.OnPropertyChanged("ipg_ResponseId");
			}
		}
		
		/// <summary>
		/// The response status. Duplicate of EBVResponse.Status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_responsestatus")]
		public string ipg_ResponseStatus
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_responsestatus");
			}
			set
			{
				this.OnPropertyChanging("ipg_ResponseStatus");
				this.SetAttributeValue("ipg_responsestatus", value);
				this.OnPropertyChanged("ipg_ResponseStatus");
			}
		}
		
		/// <summary>
		/// The sender ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_senderid")]
		public string ipg_SenderId
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_senderid");
			}
			set
			{
				this.OnPropertyChanging("ipg_SenderId");
				this.SetAttributeValue("ipg_senderid", value);
				this.OnPropertyChanged("ipg_SenderId");
			}
		}
		
		/// <summary>
		/// The inquiry status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_status")]
		public string ipg_Status
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_status");
			}
			set
			{
				this.OnPropertyChanging("ipg_Status");
				this.SetAttributeValue("ipg_status", value);
				this.OnPropertyChanged("ipg_Status");
			}
		}
		
		/// <summary>
		/// The subscriber date of birth
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_subscriberdob")]
		public System.Nullable<System.DateTime> ipg_SubscriberDOB
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_subscriberdob");
			}
			set
			{
				this.OnPropertyChanging("ipg_SubscriberDOB");
				this.SetAttributeValue("ipg_subscriberdob", value);
				this.OnPropertyChanged("ipg_SubscriberDOB");
			}
		}
		
		/// <summary>
		/// The subscriber first name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_subscriberfirstname")]
		public string ipg_SubscriberFirstName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_subscriberfirstname");
			}
			set
			{
				this.OnPropertyChanging("ipg_SubscriberFirstName");
				this.SetAttributeValue("ipg_subscriberfirstname", value);
				this.OnPropertyChanged("ipg_SubscriberFirstName");
			}
		}
		
		/// <summary>
		/// The subscriber gender
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_subscribergender")]
		public string ipg_SubscriberGender
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_subscribergender");
			}
			set
			{
				this.OnPropertyChanging("ipg_SubscriberGender");
				this.SetAttributeValue("ipg_subscribergender", value);
				this.OnPropertyChanged("ipg_SubscriberGender");
			}
		}
		
		/// <summary>
		/// The subscriber last name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_subscriberlastname")]
		public string ipg_SubscriberLastName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_subscriberlastname");
			}
			set
			{
				this.OnPropertyChanging("ipg_SubscriberLastName");
				this.SetAttributeValue("ipg_subscriberlastname", value);
				this.OnPropertyChanged("ipg_SubscriberLastName");
			}
		}
		
		/// <summary>
		/// The subscriber middle name
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_subscribermiddlename")]
		public string ipg_SubscriberMiddleName
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_subscribermiddlename");
			}
			set
			{
				this.OnPropertyChanging("ipg_SubscriberMiddleName");
				this.SetAttributeValue("ipg_subscribermiddlename", value);
				this.OnPropertyChanged("ipg_SubscriberMiddleName");
			}
		}
		
		/// <summary>
		/// N:1 ipg_contact_ipg_ebvinquiry_patientid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_patientid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_contact_ipg_ebvinquiry_patientid")]
		public Insight.Intake.Contact ipg_contact_ipg_ebvinquiry_patientid
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Contact>("ipg_contact_ipg_ebvinquiry_patientid", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_contact_ipg_ebvinquiry_patientid");
				this.SetRelatedEntity<Insight.Intake.Contact>("ipg_contact_ipg_ebvinquiry_patientid", null, value);
				this.OnPropertyChanged("ipg_contact_ipg_ebvinquiry_patientid");
			}
		}
		
		/// <summary>
		/// N:1 ipg_incident_ipg_ebvinquiry_CaseId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_caseid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_incident_ipg_ebvinquiry_CaseId")]
		public Insight.Intake.Incident ipg_incident_ipg_ebvinquiry_CaseId
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Incident>("ipg_incident_ipg_ebvinquiry_CaseId", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_incident_ipg_ebvinquiry_CaseId");
				this.SetRelatedEntity<Insight.Intake.Incident>("ipg_incident_ipg_ebvinquiry_CaseId", null, value);
				this.OnPropertyChanged("ipg_incident_ipg_ebvinquiry_CaseId");
			}
		}
		
		/// <summary>
		/// N:1 ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_responseid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId")]
		public Insight.Intake.ipg_EBVResponse ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.ipg_EBVResponse>("ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId");
				this.SetRelatedEntity<Insight.Intake.ipg_EBVResponse>("ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId", null, value);
				this.OnPropertyChanged("ipg_ipg_ebvresponse_ipg_ebvinquiry_ResponseId");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public ipg_EBVInquiry(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ipg_ebvinquiryid"] = base.Id;
                        break;
                    case "ipg_ebvinquiryid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}