//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum ipg_paymentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// The entity to record the Payments
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ipg_payment")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class ipg_payment : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ipg_AboveBelowEST = "ipg_abovebelowest";
			public const string ipg_abovebelowest_Base = "ipg_abovebelowest_base";
			public const string ipg_AdjustmentType = "ipg_adjustmenttype";
			public const string ipg_Amount = "ipg_amount";
			public const string ipg_amount_Base = "ipg_amount_base";
			public const string ipg_amount_patient_resp = "ipg_amount_patient_resp";
			public const string ipg_amount_patient_resp_new = "ipg_amount_patient_resp_new";
			public const string ipg_amount_patient_resp_new_Base = "ipg_amount_patient_resp_new_base";
			public const string ipg_AmountToApply = "ipg_amounttoapply";
			public const string ipg_amounttoapply_Base = "ipg_amounttoapply_base";
			public const string ipg_AmountType = "ipg_amounttype";
			public const string ipg_ApplyAdjustment = "ipg_applyadjustment";
			public const string ipg_ApplyTo = "ipg_applyto";
			public const string ipg_ar_carrieradj = "ipg_ar_carrieradj";
			public const string ipg_ar_carrierbalance = "ipg_ar_carrierbalance";
			public const string ipg_ar_carrierpaid = "ipg_ar_carrierpaid";
			public const string ipg_ar_carrierprevadj = "ipg_ar_carrierprevadj";
			public const string ipg_ar_carriersalesadj = "ipg_ar_carriersalesadj";
			public const string ipg_ar_carrierwriteoff = "ipg_ar_carrierwriteoff";
			public const string ipg_ar_memberadj = "ipg_ar_memberadj";
			public const string ipg_ar_memberbalance = "ipg_ar_memberbalance";
			public const string ipg_ar_memberest = "ipg_ar_memberest";
			public const string ipg_ar_memberpd = "ipg_ar_memberpd";
			public const string ipg_ar_memberprevadj = "ipg_ar_memberprevadj";
			public const string ipg_ar_memberprevsalesadj = "ipg_ar_memberprevsalesadj";
			public const string ipg_ar_membersalesadj = "ipg_ar_membersalesadj";
			public const string ipg_ar_totaladj = "ipg_ar_totaladj";
			public const string ipg_ar_totalbal = "ipg_ar_totalbal";
			public const string ipg_ar_totalest = "ipg_ar_totalest";
			public const string ipg_ar_totalpd = "ipg_ar_totalpd";
			public const string ipg_ArCarrierEst = "ipg_arcarrierest";
			public const string ipg_armemberadjreason = "ipg_armemberadjreason";
			public const string ipg_armembersalesadj = "ipg_armembersalesadj";
			public const string ipg_ARMemberWriteoff = "ipg_armemberwriteoff";
			public const string ipg_balance = "ipg_balance";
			public const string ipg_caradjcur = "ipg_caradjcur";
			public const string ipg_caradjprev = "ipg_caradjprev";
			public const string ipg_CarrierCoInsurance = "ipg_carriercoinsurance";
			public const string ipg_CaseBalance = "ipg_casebalance";
			public const string ipg_casebalance_Base = "ipg_casebalance_base";
			public const string ipg_CaseId = "ipg_caseid";
			public const string ipg_CheckNumber = "ipg_checknumber";
			public const string ipg_Claim = "ipg_claim";
			public const string ipg_ClaimResponseHeader = "ipg_claimresponseheader";
			public const string ipg_ClaimToggle = "ipg_claimtoggle";
			public const string ipg_DeductibleDollar = "ipg_deductibledollar";
			public const string ipg_DeductibleMet = "ipg_deductiblemet";
			public const string ipg_dmecap = "ipg_dmecap";
			public const string ipg_From = "ipg_from";
			public const string ipg_icn = "ipg_icn";
			public const string ipg_InsBalance = "ipg_insbalance";
			public const string ipg_insresp = "ipg_insresp";
			public const string ipg_InterestAdjustment = "ipg_interestadjustment";
			public const string ipg_InterestPayment = "ipg_interestpayment";
			public const string ipg_interestpayment_Base = "ipg_interestpayment_base";
			public const string ipg_LifetimeMax = "ipg_lifetimemax";
			public const string ipg_LifetimeMet = "ipg_lifetimemet";
			public const string ipg_MaxInsurance = "ipg_maxinsurance";
			public const string ipg_MaxPtResp = "ipg_maxptresp";
			public const string ipg_memadjprev = "ipg_memadjprev";
			public const string ipg_MemberBalance = "ipg_memberbalance";
			public const string ipg_MemberCoInsurance = "ipg_membercoinsurance";
			public const string ipg_MemberOopMax = "ipg_memberoopmax";
			public const string ipg_memberoopmax_Base = "ipg_memberoopmax_base";
			public const string ipg_MemberOopMet = "ipg_memberoopmet";
			public const string ipg_memberoopmet_Base = "ipg_memberoopmet_base";
			public const string ipg_MemberPaid = "ipg_memberpaid";
			public const string ipg_MemberPaid_new = "ipg_memberpaid_new";
			public const string ipg_memberpaid_new_Base = "ipg_memberpaid_new_base";
			public const string ipg_MemberPaidPrevious = "ipg_memberpaidprevious";
			public const string ipg_memberrespnew = "ipg_memberrespnew";
			public const string ipg_name = "ipg_name";
			public const string ipg_Note = "ipg_note";
			public const string ipg_Notes = "ipg_notes";
			public const string ipg_OPMaxInsurance = "ipg_opmaxinsurance";
			public const string ipg_patientid = "ipg_patientid";
			public const string ipg_Payment = "ipg_payment";
			public const string ipg_PaymentAge = "ipg_paymentage";
			public const string ipg_PaymentAmount = "ipg_paymentamount";
			public const string ipg_paymentamount_Base = "ipg_paymentamount_base";
			public const string ipg_PaymentDate = "ipg_paymentdate";
			public const string ipg_paymentId = "ipg_paymentid";
			public const string Id = "ipg_paymentid";
			public const string ipg_PaymentType = "ipg_paymenttype";
			public const string ipg_Percent = "ipg_percent";
			public const string ipg_Reason = "ipg_reason";
			public const string ipg_refundamount = "ipg_refundamount";
			public const string ipg_refundamount_new = "ipg_refundamount_new";
			public const string ipg_refundamount_new_Base = "ipg_refundamount_new_base";
			public const string ipg_refundchecknumber = "ipg_refundchecknumber";
			public const string ipg_RefundDate = "ipg_refunddate";
			public const string ipg_RemainingCarrierBalance = "ipg_remainingcarrierbalance";
			public const string ipg_remainingcarrierbalance_Base = "ipg_remainingcarrierbalance_base";
			public const string ipg_RemainingPatientBalance = "ipg_remainingpatientbalance";
			public const string ipg_remainingpatientbalance_Base = "ipg_remainingpatientbalance_base";
			public const string ipg_RemainingSecondaryCarrierBalance = "ipg_remainingsecondarycarrierbalance";
			public const string ipg_remainingsecondarycarrierbalance_Base = "ipg_remainingsecondarycarrierbalance_base";
			public const string ipg_To = "ipg_to";
			public const string ipg_TotalInsurancePaid = "ipg_totalinsurancepaid";
			public const string ipg_UnmetDeductible = "ipg_unmetdeductible";
			public const string ipg_WriteOffamount = "ipg_writeoffamount";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_ipg_payment = "business_unit_ipg_payment";
			public const string ipg_contact_ipg_payment_patientid = "ipg_contact_ipg_payment_patientid";
			public const string ipg_incident_ipg_payment_CaseId = "ipg_incident_ipg_payment_CaseId";
			public const string ipg_invoice_ipg_payment_Claim = "ipg_invoice_ipg_payment_Claim";
			public const string ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader = "ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader";
			public const string lk_ipg_payment_createdby = "lk_ipg_payment_createdby";
			public const string lk_ipg_payment_createdonbehalfby = "lk_ipg_payment_createdonbehalfby";
			public const string lk_ipg_payment_modifiedby = "lk_ipg_payment_modifiedby";
			public const string lk_ipg_payment_modifiedonbehalfby = "lk_ipg_payment_modifiedonbehalfby";
			public const string team_ipg_payment = "team_ipg_payment";
			public const string TransactionCurrency_ipg_payment = "TransactionCurrency_ipg_payment";
			public const string user_ipg_payment = "user_ipg_payment";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ipg_payment() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "ipg_payment";
		
		public const string EntitySchemaName = "ipg_payment";
		
		public const string PrimaryIdAttribute = "ipg_paymentid";
		
		public const string PrimaryNameAttribute = "ipg_name";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Amount above-below estimate (current payment + total paid - estimate)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_abovebelowest")]
		public Microsoft.Xrm.Sdk.Money ipg_AboveBelowEST
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_abovebelowest");
			}
			set
			{
				this.OnPropertyChanging("ipg_AboveBelowEST");
				this.SetAttributeValue("ipg_abovebelowest", value);
				this.OnPropertyChanged("ipg_AboveBelowEST");
			}
		}
		
		/// <summary>
		/// Value of the Above Below EST in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_abovebelowest_base")]
		public Microsoft.Xrm.Sdk.Money ipg_abovebelowest_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_abovebelowest_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_adjustmenttype")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_AdjustmentType
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_adjustmenttype");
			}
			set
			{
				this.OnPropertyChanging("ipg_AdjustmentType");
				this.SetAttributeValue("ipg_adjustmenttype", value);
				this.OnPropertyChanged("ipg_AdjustmentType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_adjustmenttype")]
		public virtual ipg_AdjustmentTypes? ipg_AdjustmentTypeEnum
		{
			get
			{
				return ((ipg_AdjustmentTypes?)(EntityOptionSetEnum.GetEnum(this, "ipg_adjustmenttype")));
			}
			set
			{
				this.OnPropertyChanging("ipg_AdjustmentType");
				this.SetAttributeValue("ipg_adjustmenttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_AdjustmentType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amount")]
		public Microsoft.Xrm.Sdk.Money ipg_Amount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_amount");
			}
			set
			{
				this.OnPropertyChanging("ipg_Amount");
				this.SetAttributeValue("ipg_amount", value);
				this.OnPropertyChanged("ipg_Amount");
			}
		}
		
		/// <summary>
		/// Value of the Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amount_base")]
		public Microsoft.Xrm.Sdk.Money ipg_amount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_amount_base");
			}
		}
		
		/// <summary>
		/// Amount of Patient Responsibility
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amount_patient_resp")]
		public System.Nullable<double> ipg_amount_patient_resp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_amount_patient_resp");
			}
			set
			{
				this.OnPropertyChanging("ipg_amount_patient_resp");
				this.SetAttributeValue("ipg_amount_patient_resp", value);
				this.OnPropertyChanged("ipg_amount_patient_resp");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amount_patient_resp_new")]
		public Microsoft.Xrm.Sdk.Money ipg_amount_patient_resp_new
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_amount_patient_resp_new");
			}
			set
			{
				this.OnPropertyChanging("ipg_amount_patient_resp_new");
				this.SetAttributeValue("ipg_amount_patient_resp_new", value);
				this.OnPropertyChanged("ipg_amount_patient_resp_new");
			}
		}
		
		/// <summary>
		/// Value of the Amount of Patient Responsibility in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amount_patient_resp_new_base")]
		public Microsoft.Xrm.Sdk.Money ipg_amount_patient_resp_new_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_amount_patient_resp_new_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amounttoapply")]
		public Microsoft.Xrm.Sdk.Money ipg_AmountToApply
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_amounttoapply");
			}
			set
			{
				this.OnPropertyChanging("ipg_AmountToApply");
				this.SetAttributeValue("ipg_amounttoapply", value);
				this.OnPropertyChanged("ipg_AmountToApply");
			}
		}
		
		/// <summary>
		/// Value of the Amount To Apply in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amounttoapply_base")]
		public Microsoft.Xrm.Sdk.Money ipg_amounttoapply_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_amounttoapply_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_amounttype")]
		public System.Nullable<bool> ipg_AmountType
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_amounttype");
			}
			set
			{
				this.OnPropertyChanging("ipg_AmountType");
				this.SetAttributeValue("ipg_amounttype", value);
				this.OnPropertyChanged("ipg_AmountType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_applyadjustment")]
		public System.Nullable<bool> ipg_ApplyAdjustment
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_applyadjustment");
			}
			set
			{
				this.OnPropertyChanging("ipg_ApplyAdjustment");
				this.SetAttributeValue("ipg_applyadjustment", value);
				this.OnPropertyChanged("ipg_ApplyAdjustment");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_applyto")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_ApplyTo
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_applyto");
			}
			set
			{
				this.OnPropertyChanging("ipg_ApplyTo");
				this.SetAttributeValue("ipg_applyto", value);
				this.OnPropertyChanged("ipg_ApplyTo");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_applyto")]
		public virtual ipg_PayerType? ipg_ApplyToEnum
		{
			get
			{
				return ((ipg_PayerType?)(EntityOptionSetEnum.GetEnum(this, "ipg_applyto")));
			}
			set
			{
				this.OnPropertyChanging("ipg_ApplyTo");
				this.SetAttributeValue("ipg_applyto", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_ApplyTo");
			}
		}
		
		/// <summary>
		/// AR carrier Adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_carrieradj")]
		public System.Nullable<double> ipg_ar_carrieradj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_carrieradj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_carrieradj");
				this.SetAttributeValue("ipg_ar_carrieradj", value);
				this.OnPropertyChanged("ipg_ar_carrieradj");
			}
		}
		
		/// <summary>
		/// AR Carrier Balance
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_carrierbalance")]
		public System.Nullable<double> ipg_ar_carrierbalance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_carrierbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_carrierbalance");
				this.SetAttributeValue("ipg_ar_carrierbalance", value);
				this.OnPropertyChanged("ipg_ar_carrierbalance");
			}
		}
		
		/// <summary>
		/// Ar Carrier Paid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_carrierpaid")]
		public System.Nullable<double> ipg_ar_carrierpaid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_carrierpaid");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_carrierpaid");
				this.SetAttributeValue("ipg_ar_carrierpaid", value);
				this.OnPropertyChanged("ipg_ar_carrierpaid");
			}
		}
		
		/// <summary>
		/// AR previous carrier adjustments
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_carrierprevadj")]
		public System.Nullable<double> ipg_ar_carrierprevadj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_carrierprevadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_carrierprevadj");
				this.SetAttributeValue("ipg_ar_carrierprevadj", value);
				this.OnPropertyChanged("ipg_ar_carrierprevadj");
			}
		}
		
		/// <summary>
		/// AR Carrier Sales Adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_carriersalesadj")]
		public System.Nullable<double> ipg_ar_carriersalesadj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_carriersalesadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_carriersalesadj");
				this.SetAttributeValue("ipg_ar_carriersalesadj", value);
				this.OnPropertyChanged("ipg_ar_carriersalesadj");
			}
		}
		
		/// <summary>
		/// AR Carrier Writeoff
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_carrierwriteoff")]
		public System.Nullable<double> ipg_ar_carrierwriteoff
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_carrierwriteoff");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_carrierwriteoff");
				this.SetAttributeValue("ipg_ar_carrierwriteoff", value);
				this.OnPropertyChanged("ipg_ar_carrierwriteoff");
			}
		}
		
		/// <summary>
		/// AR Member Adjustments
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_memberadj")]
		public System.Nullable<double> ipg_ar_memberadj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_memberadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_memberadj");
				this.SetAttributeValue("ipg_ar_memberadj", value);
				this.OnPropertyChanged("ipg_ar_memberadj");
			}
		}
		
		/// <summary>
		/// AR Member Balance
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_memberbalance")]
		public System.Nullable<double> ipg_ar_memberbalance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_memberbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_memberbalance");
				this.SetAttributeValue("ipg_ar_memberbalance", value);
				this.OnPropertyChanged("ipg_ar_memberbalance");
			}
		}
		
		/// <summary>
		/// AR Member Estimate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_memberest")]
		public System.Nullable<double> ipg_ar_memberest
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_memberest");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_memberest");
				this.SetAttributeValue("ipg_ar_memberest", value);
				this.OnPropertyChanged("ipg_ar_memberest");
			}
		}
		
		/// <summary>
		/// AR Member Paid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_memberpd")]
		public System.Nullable<double> ipg_ar_memberpd
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_memberpd");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_memberpd");
				this.SetAttributeValue("ipg_ar_memberpd", value);
				this.OnPropertyChanged("ipg_ar_memberpd");
			}
		}
		
		/// <summary>
		/// AR Member Previous Adjustments
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_memberprevadj")]
		public System.Nullable<double> ipg_ar_memberprevadj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_memberprevadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_memberprevadj");
				this.SetAttributeValue("ipg_ar_memberprevadj", value);
				this.OnPropertyChanged("ipg_ar_memberprevadj");
			}
		}
		
		/// <summary>
		/// AR Member Previous Sales Adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_memberprevsalesadj")]
		public string ipg_ar_memberprevsalesadj
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_ar_memberprevsalesadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_memberprevsalesadj");
				this.SetAttributeValue("ipg_ar_memberprevsalesadj", value);
				this.OnPropertyChanged("ipg_ar_memberprevsalesadj");
			}
		}
		
		/// <summary>
		/// Member Sales Adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_membersalesadj")]
		public System.Nullable<double> ipg_ar_membersalesadj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_membersalesadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_membersalesadj");
				this.SetAttributeValue("ipg_ar_membersalesadj", value);
				this.OnPropertyChanged("ipg_ar_membersalesadj");
			}
		}
		
		/// <summary>
		/// AR Total Adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_totaladj")]
		public System.Nullable<double> ipg_ar_totaladj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_totaladj");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_totaladj");
				this.SetAttributeValue("ipg_ar_totaladj", value);
				this.OnPropertyChanged("ipg_ar_totaladj");
			}
		}
		
		/// <summary>
		/// AR Total balance
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_totalbal")]
		public System.Nullable<double> ipg_ar_totalbal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_totalbal");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_totalbal");
				this.SetAttributeValue("ipg_ar_totalbal", value);
				this.OnPropertyChanged("ipg_ar_totalbal");
			}
		}
		
		/// <summary>
		/// AR Total Estimate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_totalest")]
		public System.Nullable<double> ipg_ar_totalest
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_totalest");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_totalest");
				this.SetAttributeValue("ipg_ar_totalest", value);
				this.OnPropertyChanged("ipg_ar_totalest");
			}
		}
		
		/// <summary>
		/// AR Total Paid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_ar_totalpd")]
		public System.Nullable<double> ipg_ar_totalpd
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_ar_totalpd");
			}
			set
			{
				this.OnPropertyChanging("ipg_ar_totalpd");
				this.SetAttributeValue("ipg_ar_totalpd", value);
				this.OnPropertyChanged("ipg_ar_totalpd");
			}
		}
		
		/// <summary>
		/// Ar Carrier estimate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_arcarrierest")]
		public System.Nullable<double> ipg_ArCarrierEst
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_arcarrierest");
			}
			set
			{
				this.OnPropertyChanging("ipg_ArCarrierEst");
				this.SetAttributeValue("ipg_arcarrierest", value);
				this.OnPropertyChanged("ipg_ArCarrierEst");
			}
		}
		
		/// <summary>
		/// AR Member adjustment reason
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_armemberadjreason")]
		public string ipg_armemberadjreason
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_armemberadjreason");
			}
			set
			{
				this.OnPropertyChanging("ipg_armemberadjreason");
				this.SetAttributeValue("ipg_armemberadjreason", value);
				this.OnPropertyChanged("ipg_armemberadjreason");
			}
		}
		
		/// <summary>
		/// AR Member Sales Adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_armembersalesadj")]
		public System.Nullable<double> ipg_armembersalesadj
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_armembersalesadj");
			}
			set
			{
				this.OnPropertyChanging("ipg_armembersalesadj");
				this.SetAttributeValue("ipg_armembersalesadj", value);
				this.OnPropertyChanged("ipg_armembersalesadj");
			}
		}
		
		/// <summary>
		/// AR Member Writeoff
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_armemberwriteoff")]
		public System.Nullable<double> ipg_ARMemberWriteoff
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_armemberwriteoff");
			}
			set
			{
				this.OnPropertyChanging("ipg_ARMemberWriteoff");
				this.SetAttributeValue("ipg_armemberwriteoff", value);
				this.OnPropertyChanged("ipg_ARMemberWriteoff");
			}
		}
		
		/// <summary>
		/// The balance remaining on the case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_balance")]
		public System.Nullable<double> ipg_balance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_balance");
			}
			set
			{
				this.OnPropertyChanging("ipg_balance");
				this.SetAttributeValue("ipg_balance", value);
				this.OnPropertyChanged("ipg_balance");
			}
		}
		
		/// <summary>
		/// Current carrier adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_caradjcur")]
		public System.Nullable<double> ipg_caradjcur
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_caradjcur");
			}
			set
			{
				this.OnPropertyChanging("ipg_caradjcur");
				this.SetAttributeValue("ipg_caradjcur", value);
				this.OnPropertyChanged("ipg_caradjcur");
			}
		}
		
		/// <summary>
		/// Previous carrier Adjustments
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_caradjprev")]
		public System.Nullable<double> ipg_caradjprev
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_caradjprev");
			}
			set
			{
				this.OnPropertyChanging("ipg_caradjprev");
				this.SetAttributeValue("ipg_caradjprev", value);
				this.OnPropertyChanged("ipg_caradjprev");
			}
		}
		
		/// <summary>
		/// The carrier co-Insurance  for the patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_carriercoinsurance")]
		public System.Nullable<double> ipg_CarrierCoInsurance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_carriercoinsurance");
			}
			set
			{
				this.OnPropertyChanging("ipg_CarrierCoInsurance");
				this.SetAttributeValue("ipg_carriercoinsurance", value);
				this.OnPropertyChanged("ipg_CarrierCoInsurance");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_casebalance")]
		public Microsoft.Xrm.Sdk.Money ipg_CaseBalance
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_casebalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_CaseBalance");
				this.SetAttributeValue("ipg_casebalance", value);
				this.OnPropertyChanged("ipg_CaseBalance");
			}
		}
		
		/// <summary>
		/// Value of the Case Balance in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_casebalance_base")]
		public Microsoft.Xrm.Sdk.Money ipg_casebalance_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_casebalance_base");
			}
		}
		
		/// <summary>
		/// The case of this payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_caseid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_CaseId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_caseid");
			}
			set
			{
				this.OnPropertyChanging("ipg_CaseId");
				this.SetAttributeValue("ipg_caseid", value);
				this.OnPropertyChanged("ipg_CaseId");
			}
		}
		
		/// <summary>
		/// The Check number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_checknumber")]
		public string ipg_CheckNumber
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_checknumber");
			}
			set
			{
				this.OnPropertyChanging("ipg_CheckNumber");
				this.SetAttributeValue("ipg_checknumber", value);
				this.OnPropertyChanged("ipg_CheckNumber");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_claim")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_Claim
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_claim");
			}
			set
			{
				this.OnPropertyChanging("ipg_Claim");
				this.SetAttributeValue("ipg_claim", value);
				this.OnPropertyChanged("ipg_Claim");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_claimresponseheader")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_ClaimResponseHeader
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_claimresponseheader");
			}
			set
			{
				this.OnPropertyChanging("ipg_ClaimResponseHeader");
				this.SetAttributeValue("ipg_claimresponseheader", value);
				this.OnPropertyChanged("ipg_ClaimResponseHeader");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_claimtoggle")]
		public System.Nullable<bool> ipg_ClaimToggle
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ipg_claimtoggle");
			}
			set
			{
				this.OnPropertyChanging("ipg_ClaimToggle");
				this.SetAttributeValue("ipg_claimtoggle", value);
				this.OnPropertyChanged("ipg_ClaimToggle");
			}
		}
		
		/// <summary>
		/// The deductible dollar amount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_deductibledollar")]
		public System.Nullable<decimal> ipg_DeductibleDollar
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("ipg_deductibledollar");
			}
			set
			{
				this.OnPropertyChanging("ipg_DeductibleDollar");
				this.SetAttributeValue("ipg_deductibledollar", value);
				this.OnPropertyChanged("ipg_DeductibleDollar");
			}
		}
		
		/// <summary>
		/// The Deductible met for this patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_deductiblemet")]
		public System.Nullable<decimal> ipg_DeductibleMet
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("ipg_deductiblemet");
			}
			set
			{
				this.OnPropertyChanging("ipg_DeductibleMet");
				this.SetAttributeValue("ipg_deductiblemet", value);
				this.OnPropertyChanged("ipg_DeductibleMet");
			}
		}
		
		/// <summary>
		/// The dmecap for this payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_dmecap")]
		public System.Nullable<double> ipg_dmecap
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_dmecap");
			}
			set
			{
				this.OnPropertyChanging("ipg_dmecap");
				this.SetAttributeValue("ipg_dmecap", value);
				this.OnPropertyChanged("ipg_dmecap");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_from")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_From
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_from");
			}
			set
			{
				this.OnPropertyChanging("ipg_From");
				this.SetAttributeValue("ipg_from", value);
				this.OnPropertyChanged("ipg_From");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_from")]
		public virtual ipg_PayerType? ipg_FromEnum
		{
			get
			{
				return ((ipg_PayerType?)(EntityOptionSetEnum.GetEnum(this, "ipg_from")));
			}
			set
			{
				this.OnPropertyChanging("ipg_From");
				this.SetAttributeValue("ipg_from", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_From");
			}
		}
		
		/// <summary>
		/// The balance to be paid by the insurance company
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_insbalance")]
		public System.Nullable<double> ipg_InsBalance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_insbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_InsBalance");
				this.SetAttributeValue("ipg_insbalance", value);
				this.OnPropertyChanged("ipg_InsBalance");
			}
		}
		
		/// <summary>
		/// The amount for which Insurance company is  responsible for
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_insresp")]
		public System.Nullable<double> ipg_insresp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_insresp");
			}
			set
			{
				this.OnPropertyChanging("ipg_insresp");
				this.SetAttributeValue("ipg_insresp", value);
				this.OnPropertyChanged("ipg_insresp");
			}
		}
		
		/// <summary>
		/// Adjustment of the interest
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_interestadjustment")]
		public System.Nullable<decimal> ipg_InterestAdjustment
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("ipg_interestadjustment");
			}
			set
			{
				this.OnPropertyChanging("ipg_InterestAdjustment");
				this.SetAttributeValue("ipg_interestadjustment", value);
				this.OnPropertyChanged("ipg_InterestAdjustment");
			}
		}
		
		/// <summary>
		/// The Interest Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_interestpayment")]
		public Microsoft.Xrm.Sdk.Money ipg_InterestPayment
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_interestpayment");
			}
			set
			{
				this.OnPropertyChanging("ipg_InterestPayment");
				this.SetAttributeValue("ipg_interestpayment", value);
				this.OnPropertyChanged("ipg_InterestPayment");
			}
		}
		
		/// <summary>
		/// Value of the Interest Payment in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_interestpayment_base")]
		public Microsoft.Xrm.Sdk.Money ipg_interestpayment_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_interestpayment_base");
			}
		}
		
		/// <summary>
		/// The lifetime maximum of a patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_lifetimemax")]
		public System.Nullable<decimal> ipg_LifetimeMax
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("ipg_lifetimemax");
			}
			set
			{
				this.OnPropertyChanging("ipg_LifetimeMax");
				this.SetAttributeValue("ipg_lifetimemax", value);
				this.OnPropertyChanged("ipg_LifetimeMax");
			}
		}
		
		/// <summary>
		/// The lifetime amount met of the patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_lifetimemet")]
		public System.Nullable<decimal> ipg_LifetimeMet
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("ipg_lifetimemet");
			}
			set
			{
				this.OnPropertyChanging("ipg_LifetimeMet");
				this.SetAttributeValue("ipg_lifetimemet", value);
				this.OnPropertyChanged("ipg_LifetimeMet");
			}
		}
		
		/// <summary>
		/// The maximum amount paid by the insurance company
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_maxinsurance")]
		public System.Nullable<double> ipg_MaxInsurance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_maxinsurance");
			}
			set
			{
				this.OnPropertyChanging("ipg_MaxInsurance");
				this.SetAttributeValue("ipg_maxinsurance", value);
				this.OnPropertyChanged("ipg_MaxInsurance");
			}
		}
		
		/// <summary>
		/// Maximum patient responsibility
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_maxptresp")]
		public System.Nullable<double> ipg_MaxPtResp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_maxptresp");
			}
			set
			{
				this.OnPropertyChanging("ipg_MaxPtResp");
				this.SetAttributeValue("ipg_maxptresp", value);
				this.OnPropertyChanged("ipg_MaxPtResp");
			}
		}
		
		/// <summary>
		/// Previous member adjustment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memadjprev")]
		public System.Nullable<double> ipg_memadjprev
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_memadjprev");
			}
			set
			{
				this.OnPropertyChanging("ipg_memadjprev");
				this.SetAttributeValue("ipg_memadjprev", value);
				this.OnPropertyChanged("ipg_memadjprev");
			}
		}
		
		/// <summary>
		/// The balance remaining for the patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberbalance")]
		public System.Nullable<double> ipg_MemberBalance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_memberbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberBalance");
				this.SetAttributeValue("ipg_memberbalance", value);
				this.OnPropertyChanged("ipg_MemberBalance");
			}
		}
		
		/// <summary>
		/// The co-Insurence of the patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_membercoinsurance")]
		public System.Nullable<double> ipg_MemberCoInsurance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_membercoinsurance");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberCoInsurance");
				this.SetAttributeValue("ipg_membercoinsurance", value);
				this.OnPropertyChanged("ipg_MemberCoInsurance");
			}
		}
		
		/// <summary>
		/// The Member OOP Max
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberoopmax")]
		public Microsoft.Xrm.Sdk.Money ipg_MemberOopMax
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_memberoopmax");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberOopMax");
				this.SetAttributeValue("ipg_memberoopmax", value);
				this.OnPropertyChanged("ipg_MemberOopMax");
			}
		}
		
		/// <summary>
		/// Value of the Member OOP Max in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberoopmax_base")]
		public Microsoft.Xrm.Sdk.Money ipg_memberoopmax_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_memberoopmax_base");
			}
		}
		
		/// <summary>
		/// The member OOP met
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberoopmet")]
		public Microsoft.Xrm.Sdk.Money ipg_MemberOopMet
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_memberoopmet");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberOopMet");
				this.SetAttributeValue("ipg_memberoopmet", value);
				this.OnPropertyChanged("ipg_MemberOopMet");
			}
		}
		
		/// <summary>
		/// Value of the Member OOP Met in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberoopmet_base")]
		public Microsoft.Xrm.Sdk.Money ipg_memberoopmet_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_memberoopmet_base");
			}
		}
		
		/// <summary>
		/// The amount member paid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberpaid")]
		public System.Nullable<double> ipg_MemberPaid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_memberpaid");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberPaid");
				this.SetAttributeValue("ipg_memberpaid", value);
				this.OnPropertyChanged("ipg_MemberPaid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberpaid_new")]
		public Microsoft.Xrm.Sdk.Money ipg_MemberPaid_new
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_memberpaid_new");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberPaid_new");
				this.SetAttributeValue("ipg_memberpaid_new", value);
				this.OnPropertyChanged("ipg_MemberPaid_new");
			}
		}
		
		/// <summary>
		/// Value of the Member Paid in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberpaid_new_base")]
		public Microsoft.Xrm.Sdk.Money ipg_memberpaid_new_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_memberpaid_new_base");
			}
		}
		
		/// <summary>
		/// The amount member paid previously
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberpaidprevious")]
		public System.Nullable<double> ipg_MemberPaidPrevious
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_memberpaidprevious");
			}
			set
			{
				this.OnPropertyChanging("ipg_MemberPaidPrevious");
				this.SetAttributeValue("ipg_memberpaidprevious", value);
				this.OnPropertyChanged("ipg_MemberPaidPrevious");
			}
		}
		
		/// <summary>
		/// New member responsibility after payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_memberrespnew")]
		public System.Nullable<double> ipg_memberrespnew
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_memberrespnew");
			}
			set
			{
				this.OnPropertyChanging("ipg_memberrespnew");
				this.SetAttributeValue("ipg_memberrespnew", value);
				this.OnPropertyChanged("ipg_memberrespnew");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_name")]
		public string ipg_name
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_name");
			}
			set
			{
				this.OnPropertyChanging("ipg_name");
				this.SetAttributeValue("ipg_name", value);
				this.OnPropertyChanged("ipg_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_note")]
		public string ipg_Note
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_note");
			}
			set
			{
				this.OnPropertyChanging("ipg_Note");
				this.SetAttributeValue("ipg_note", value);
				this.OnPropertyChanged("ipg_Note");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_notes")]
		public string ipg_Notes
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_notes");
			}
			set
			{
				this.OnPropertyChanging("ipg_Notes");
				this.SetAttributeValue("ipg_notes", value);
				this.OnPropertyChanged("ipg_Notes");
			}
		}
		
		/// <summary>
		/// The Out of Pocket Max Insurance
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_opmaxinsurance")]
		public System.Nullable<double> ipg_OPMaxInsurance
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_opmaxinsurance");
			}
			set
			{
				this.OnPropertyChanging("ipg_OPMaxInsurance");
				this.SetAttributeValue("ipg_opmaxinsurance", value);
				this.OnPropertyChanged("ipg_OPMaxInsurance");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_patientid")]
		public Microsoft.Xrm.Sdk.EntityReference ipg_patientid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ipg_patientid");
			}
			set
			{
				this.OnPropertyChanging("ipg_patientid");
				this.SetAttributeValue("ipg_patientid", value);
				this.OnPropertyChanged("ipg_patientid");
			}
		}
		
		/// <summary>
		/// The amount paid in full or partial
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_payment")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_Payment
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_payment");
			}
			set
			{
				this.OnPropertyChanging("ipg_Payment");
				this.SetAttributeValue("ipg_payment", value);
				this.OnPropertyChanged("ipg_Payment");
			}
		}
		
		/// <summary>
		/// The amount paid in full or partial
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_payment")]
		public virtual ipg_Payment1? ipg_PaymentEnum
		{
			get
			{
				return ((ipg_Payment1?)(EntityOptionSetEnum.GetEnum(this, "ipg_payment")));
			}
			set
			{
				this.OnPropertyChanging("ipg_Payment");
				this.SetAttributeValue("ipg_payment", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_Payment");
			}
		}
		
		/// <summary>
		/// payment_age (in days) = DOS - payment_collected
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymentage")]
		public System.Nullable<int> ipg_PaymentAge
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("ipg_paymentage");
			}
			set
			{
				this.OnPropertyChanging("ipg_PaymentAge");
				this.SetAttributeValue("ipg_paymentage", value);
				this.OnPropertyChanged("ipg_PaymentAge");
			}
		}
		
		/// <summary>
		/// The amount on the payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymentamount")]
		public Microsoft.Xrm.Sdk.Money ipg_PaymentAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_paymentamount");
			}
			set
			{
				this.OnPropertyChanging("ipg_PaymentAmount");
				this.SetAttributeValue("ipg_paymentamount", value);
				this.OnPropertyChanged("ipg_PaymentAmount");
			}
		}
		
		/// <summary>
		/// Value of the Payment Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymentamount_base")]
		public Microsoft.Xrm.Sdk.Money ipg_paymentamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_paymentamount_base");
			}
		}
		
		/// <summary>
		/// The date when the payment was recorded
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymentdate")]
		public System.Nullable<System.DateTime> ipg_PaymentDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_paymentdate");
			}
			set
			{
				this.OnPropertyChanging("ipg_PaymentDate");
				this.SetAttributeValue("ipg_paymentdate", value);
				this.OnPropertyChanged("ipg_PaymentDate");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymentid")]
		public System.Nullable<System.Guid> ipg_paymentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ipg_paymentid");
			}
			set
			{
				this.OnPropertyChanging("ipg_paymentId");
				this.SetAttributeValue("ipg_paymentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("ipg_paymentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ipg_paymentId = value;
			}
		}
		
		/// <summary>
		/// The type of payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymenttype")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_PaymentType
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_paymenttype");
			}
			set
			{
				this.OnPropertyChanging("ipg_PaymentType");
				this.SetAttributeValue("ipg_paymenttype", value);
				this.OnPropertyChanged("ipg_PaymentType");
			}
		}
		
		/// <summary>
		/// The type of payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_paymenttype")]
		public virtual ipg_PaymentType? ipg_PaymentTypeEnum
		{
			get
			{
				return ((ipg_PaymentType?)(EntityOptionSetEnum.GetEnum(this, "ipg_paymenttype")));
			}
			set
			{
				this.OnPropertyChanging("ipg_PaymentType");
				this.SetAttributeValue("ipg_paymenttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_PaymentType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_percent")]
		public System.Nullable<int> ipg_Percent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("ipg_percent");
			}
			set
			{
				this.OnPropertyChanging("ipg_Percent");
				this.SetAttributeValue("ipg_percent", value);
				this.OnPropertyChanged("ipg_Percent");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_reason")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_Reason
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_reason");
			}
			set
			{
				this.OnPropertyChanging("ipg_Reason");
				this.SetAttributeValue("ipg_reason", value);
				this.OnPropertyChanged("ipg_Reason");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_reason")]
		public virtual ipg_AdjustmentReasons? ipg_ReasonEnum
		{
			get
			{
				return ((ipg_AdjustmentReasons?)(EntityOptionSetEnum.GetEnum(this, "ipg_reason")));
			}
			set
			{
				this.OnPropertyChanging("ipg_Reason");
				this.SetAttributeValue("ipg_reason", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_Reason");
			}
		}
		
		/// <summary>
		/// Refund Amount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_refundamount")]
		public System.Nullable<double> ipg_refundamount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_refundamount");
			}
			set
			{
				this.OnPropertyChanging("ipg_refundamount");
				this.SetAttributeValue("ipg_refundamount", value);
				this.OnPropertyChanged("ipg_refundamount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_refundamount_new")]
		public Microsoft.Xrm.Sdk.Money ipg_refundamount_new
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_refundamount_new");
			}
			set
			{
				this.OnPropertyChanging("ipg_refundamount_new");
				this.SetAttributeValue("ipg_refundamount_new", value);
				this.OnPropertyChanged("ipg_refundamount_new");
			}
		}
		
		/// <summary>
		/// Value of the Refund Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_refundamount_new_base")]
		public Microsoft.Xrm.Sdk.Money ipg_refundamount_new_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_refundamount_new_base");
			}
		}
		
		/// <summary>
		/// Refund Check Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_refundchecknumber")]
		public string ipg_refundchecknumber
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_refundchecknumber");
			}
			set
			{
				this.OnPropertyChanging("ipg_refundchecknumber");
				this.SetAttributeValue("ipg_refundchecknumber", value);
				this.OnPropertyChanged("ipg_refundchecknumber");
			}
		}
		
		/// <summary>
		/// Refund Date
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_refunddate")]
		public System.Nullable<System.DateTime> ipg_RefundDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ipg_refunddate");
			}
			set
			{
				this.OnPropertyChanging("ipg_RefundDate");
				this.SetAttributeValue("ipg_refunddate", value);
				this.OnPropertyChanged("ipg_RefundDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_remainingcarrierbalance")]
		public Microsoft.Xrm.Sdk.Money ipg_RemainingCarrierBalance
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_remainingcarrierbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_RemainingCarrierBalance");
				this.SetAttributeValue("ipg_remainingcarrierbalance", value);
				this.OnPropertyChanged("ipg_RemainingCarrierBalance");
			}
		}
		
		/// <summary>
		/// Value of the Remaining Carrier Balance in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_remainingcarrierbalance_base")]
		public Microsoft.Xrm.Sdk.Money ipg_remainingcarrierbalance_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_remainingcarrierbalance_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_remainingpatientbalance")]
		public Microsoft.Xrm.Sdk.Money ipg_RemainingPatientBalance
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_remainingpatientbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_RemainingPatientBalance");
				this.SetAttributeValue("ipg_remainingpatientbalance", value);
				this.OnPropertyChanged("ipg_RemainingPatientBalance");
			}
		}
		
		/// <summary>
		/// Value of the Remaining Patient Balance in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_remainingpatientbalance_base")]
		public Microsoft.Xrm.Sdk.Money ipg_remainingpatientbalance_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_remainingpatientbalance_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_remainingsecondarycarrierbalance")]
		public Microsoft.Xrm.Sdk.Money ipg_RemainingSecondaryCarrierBalance
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_remainingsecondarycarrierbalance");
			}
			set
			{
				this.OnPropertyChanging("ipg_RemainingSecondaryCarrierBalance");
				this.SetAttributeValue("ipg_remainingsecondarycarrierbalance", value);
				this.OnPropertyChanged("ipg_RemainingSecondaryCarrierBalance");
			}
		}
		
		/// <summary>
		/// Value of the Remaining Secondary Carrier Balance in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_remainingsecondarycarrierbalance_base")]
		public Microsoft.Xrm.Sdk.Money ipg_remainingsecondarycarrierbalance_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("ipg_remainingsecondarycarrierbalance_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_to")]
		public Microsoft.Xrm.Sdk.OptionSetValue ipg_To
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ipg_to");
			}
			set
			{
				this.OnPropertyChanging("ipg_To");
				this.SetAttributeValue("ipg_to", value);
				this.OnPropertyChanged("ipg_To");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_to")]
		public virtual ipg_PayerType? ipg_ToEnum
		{
			get
			{
				return ((ipg_PayerType?)(EntityOptionSetEnum.GetEnum(this, "ipg_to")));
			}
			set
			{
				this.OnPropertyChanging("ipg_To");
				this.SetAttributeValue("ipg_to", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ipg_To");
			}
		}
		
		/// <summary>
		/// The amount paid by the insurance company
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_totalinsurancepaid")]
		public System.Nullable<double> ipg_TotalInsurancePaid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_totalinsurancepaid");
			}
			set
			{
				this.OnPropertyChanging("ipg_TotalInsurancePaid");
				this.SetAttributeValue("ipg_totalinsurancepaid", value);
				this.OnPropertyChanged("ipg_TotalInsurancePaid");
			}
		}
		
		/// <summary>
		/// The dollar amount remaining on patient insurance
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_unmetdeductible")]
		public System.Nullable<double> ipg_UnmetDeductible
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_unmetdeductible");
			}
			set
			{
				this.OnPropertyChanging("ipg_UnmetDeductible");
				this.SetAttributeValue("ipg_unmetdeductible", value);
				this.OnPropertyChanged("ipg_UnmetDeductible");
			}
		}
		
		/// <summary>
		/// The amount to be written off for this patient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_writeoffamount")]
		public System.Nullable<double> ipg_WriteOffamount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("ipg_writeoffamount");
			}
			set
			{
				this.OnPropertyChanging("ipg_WriteOffamount");
				this.SetAttributeValue("ipg_writeoffamount", value);
				this.OnPropertyChanged("ipg_WriteOffamount");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Insight.Intake.ipg_paymentState> StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Insight.Intake.ipg_paymentState)(System.Enum.ToObject(typeof(Insight.Intake.ipg_paymentState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual ipg_payment_StatusCode? StatusCodeEnum
		{
			get
			{
				return ((ipg_payment_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_payment_ipg_adjustment_Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_payment_ipg_adjustment_Payment")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_adjustment> ipg_ipg_payment_ipg_adjustment_Payment
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_adjustment>("ipg_ipg_payment_ipg_adjustment_Payment", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_payment_ipg_adjustment_Payment");
				this.SetRelatedEntities<Insight.Intake.ipg_adjustment>("ipg_ipg_payment_ipg_adjustment_Payment", null, value);
				this.OnPropertyChanged("ipg_ipg_payment_ipg_adjustment_Payment");
			}
		}
		
		/// <summary>
		/// 1:N ipg_ipg_payment_ipg_gltransaction_Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_payment_ipg_gltransaction_Payment")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_GLTransaction> ipg_ipg_payment_ipg_gltransaction_Payment
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_GLTransaction>("ipg_ipg_payment_ipg_gltransaction_Payment", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_payment_ipg_gltransaction_Payment");
				this.SetRelatedEntities<Insight.Intake.ipg_GLTransaction>("ipg_ipg_payment_ipg_gltransaction_Payment", null, value);
				this.OnPropertyChanged("ipg_ipg_payment_ipg_gltransaction_Payment");
			}
		}
		
		/// <summary>
		/// 1:N ipg_payment_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_payment_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.AsyncOperation> ipg_payment_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.AsyncOperation>("ipg_payment_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_payment_AsyncOperations");
				this.SetRelatedEntities<Insight.Intake.AsyncOperation>("ipg_payment_AsyncOperations", null, value);
				this.OnPropertyChanged("ipg_payment_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N ipg_payment_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_payment_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> ipg_payment_DuplicateBaseRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_payment_DuplicateBaseRecord", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_payment_DuplicateBaseRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_payment_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("ipg_payment_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N ipg_payment_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_payment_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> ipg_payment_DuplicateMatchingRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_payment_DuplicateMatchingRecord", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_payment_DuplicateMatchingRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("ipg_payment_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("ipg_payment_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N ipg_payment_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_payment_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.PrincipalObjectAttributeAccess> ipg_payment_PrincipalObjectAttributeAccesses
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("ipg_payment_PrincipalObjectAttributeAccesses", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_payment_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("ipg_payment_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("ipg_payment_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_ipg_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_ipg_payment")]
		public Insight.Intake.BusinessUnit business_unit_ipg_payment
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.BusinessUnit>("business_unit_ipg_payment", null);
			}
		}
		
		/// <summary>
		/// N:1 ipg_contact_ipg_payment_patientid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_patientid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_contact_ipg_payment_patientid")]
		public Insight.Intake.Contact ipg_contact_ipg_payment_patientid
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Contact>("ipg_contact_ipg_payment_patientid", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_contact_ipg_payment_patientid");
				this.SetRelatedEntity<Insight.Intake.Contact>("ipg_contact_ipg_payment_patientid", null, value);
				this.OnPropertyChanged("ipg_contact_ipg_payment_patientid");
			}
		}
		
		/// <summary>
		/// N:1 ipg_incident_ipg_payment_CaseId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_caseid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_incident_ipg_payment_CaseId")]
		public Insight.Intake.Incident ipg_incident_ipg_payment_CaseId
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Incident>("ipg_incident_ipg_payment_CaseId", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_incident_ipg_payment_CaseId");
				this.SetRelatedEntity<Insight.Intake.Incident>("ipg_incident_ipg_payment_CaseId", null, value);
				this.OnPropertyChanged("ipg_incident_ipg_payment_CaseId");
			}
		}
		
		/// <summary>
		/// N:1 ipg_invoice_ipg_payment_Claim
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_claim")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_invoice_ipg_payment_Claim")]
		public Insight.Intake.Invoice ipg_invoice_ipg_payment_Claim
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Invoice>("ipg_invoice_ipg_payment_Claim", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_invoice_ipg_payment_Claim");
				this.SetRelatedEntity<Insight.Intake.Invoice>("ipg_invoice_ipg_payment_Claim", null, value);
				this.OnPropertyChanged("ipg_invoice_ipg_payment_Claim");
			}
		}
		
		/// <summary>
		/// N:1 ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_claimresponseheader")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader")]
		public Insight.Intake.ipg_claimresponseheader ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.ipg_claimresponseheader>("ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader", null);
			}
			set
			{
				this.OnPropertyChanging("ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader");
				this.SetRelatedEntity<Insight.Intake.ipg_claimresponseheader>("ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader", null, value);
				this.OnPropertyChanged("ipg_ipg_claimresponseheader_ipg_payment_ClaimResponseHeader");
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_payment_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_payment_createdby")]
		public Insight.Intake.SystemUser lk_ipg_payment_createdby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_payment_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_payment_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_payment_createdonbehalfby")]
		public Insight.Intake.SystemUser lk_ipg_payment_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_payment_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ipg_payment_createdonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_payment_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_ipg_payment_createdonbehalfby");
			}
		}

		/// <summary>
		/// icn_num in legacy. ICN number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ipg_icn")]
		public string ipg_icn
		{
			get
			{
				return this.GetAttributeValue<string>("ipg_icn");
			}
			set
			{
				this.OnPropertyChanging("ipg_icn");
				this.SetAttributeValue("ipg_icn", value);
				this.OnPropertyChanged("ipg_icn");
			}
		}
		/// <summary>
		/// N:1 lk_ipg_payment_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_payment_modifiedby")]
		public Insight.Intake.SystemUser lk_ipg_payment_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_payment_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ipg_payment_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ipg_payment_modifiedonbehalfby")]
		public Insight.Intake.SystemUser lk_ipg_payment_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_payment_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_ipg_payment_modifiedonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_ipg_payment_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_ipg_payment_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 team_ipg_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_ipg_payment")]
		public Insight.Intake.Team team_ipg_payment
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.Team>("team_ipg_payment", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_ipg_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_ipg_payment")]
		public Insight.Intake.TransactionCurrency TransactionCurrency_ipg_payment
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.TransactionCurrency>("TransactionCurrency_ipg_payment", null);
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrency_ipg_payment");
				this.SetRelatedEntity<Insight.Intake.TransactionCurrency>("TransactionCurrency_ipg_payment", null, value);
				this.OnPropertyChanged("TransactionCurrency_ipg_payment");
			}
		}
		
		/// <summary>
		/// N:1 user_ipg_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_ipg_payment")]
		public Insight.Intake.SystemUser user_ipg_payment
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("user_ipg_payment", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public ipg_payment(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ipg_paymentid"] = base.Id;
                        break;
                    case "ipg_paymentid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}