//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Intake
{
	
	/// <summary>
	/// Metadata of knowledge base (KB) articles associated with Microsoft Dynamics 365 entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("knowledgebaserecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class KnowledgeBaseRecord : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ExchangeRate = "exchangerate";
			public const string KnowledgeBaseRecordId = "knowledgebaserecordid";
			public const string Id = "knowledgebaserecordid";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string PrivateUrl = "privateurl";
			public const string PublicUrl = "publicurl";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Title = "title";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UniqueId = "uniqueid";
			public const string VersionNumber = "versionnumber";
			public const string lk_KnowledgeBaseRecord_createdby = "lk_KnowledgeBaseRecord_createdby";
			public const string lk_KnowledgeBaseRecord_createdonbehalfby = "lk_KnowledgeBaseRecord_createdonbehalfby";
			public const string lk_KnowledgeBaseRecord_modifiedby = "lk_KnowledgeBaseRecord_modifiedby";
			public const string lk_KnowledgeBaseRecord_modifiedonbehalfby = "lk_KnowledgeBaseRecord_modifiedonbehalfby";
			public const string TransactionCurrency_KnowledgeBaseRecord = "TransactionCurrency_KnowledgeBaseRecord";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public KnowledgeBaseRecord() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "knowledgebaserecord";
		
		public const string EntitySchemaName = "KnowledgeBaseRecord";
		
		public const string PrimaryIdAttribute = "knowledgebaserecordid";
		
		public const string PrimaryNameAttribute = "title";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the knowledge base record with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// This field will be used to store the Unique ID of the associated Knowledge Base records
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgebaserecordid")]
		public System.Nullable<System.Guid> KnowledgeBaseRecordId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("knowledgebaserecordid");
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecordId");
				this.SetAttributeValue("knowledgebaserecordid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("KnowledgeBaseRecordId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgebaserecordid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.KnowledgeBaseRecordId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Shows the internal Parature service desk URL of the knowledge base records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("privateurl")]
		public string PrivateUrl
		{
			get
			{
				return this.GetAttributeValue<string>("privateurl");
			}
			set
			{
				this.OnPropertyChanging("PrivateUrl");
				this.SetAttributeValue("privateurl", value);
				this.OnPropertyChanged("PrivateUrl");
			}
		}
		
		/// <summary>
		/// Shows the public Parature portal URL of the knowledge base records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publicurl")]
		public string PublicUrl
		{
			get
			{
				return this.GetAttributeValue<string>("publicurl");
			}
			set
			{
				this.OnPropertyChanging("PublicUrl");
				this.SetAttributeValue("publicurl", value);
				this.OnPropertyChanged("PublicUrl");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the title of the knowledge base (KB) Record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			set
			{
				this.OnPropertyChanging("Title");
				this.SetAttributeValue("title", value);
				this.OnPropertyChanged("Title");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the Knowledge Base Record with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Shows the unique ID of the linked knowledge base (KB) article.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniqueid")]
		public string UniqueId
		{
			get
			{
				return this.GetAttributeValue<string>("uniqueid");
			}
			set
			{
				this.OnPropertyChanging("UniqueId");
				this.SetAttributeValue("uniqueid", value);
				this.OnPropertyChanged("UniqueId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ActivityPointer> KnowledgeBaseRecord_ActivityPointers
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ActivityPointer>("KnowledgeBaseRecord_ActivityPointers", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_ActivityPointers");
				this.SetRelatedEntities<Insight.Intake.ActivityPointer>("KnowledgeBaseRecord_ActivityPointers", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_adx_portalcomments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_adx_portalcomments")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.adx_portalcomment> knowledgebaserecord_adx_portalcomments
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.adx_portalcomment>("knowledgebaserecord_adx_portalcomments", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_adx_portalcomments");
				this.SetRelatedEntities<Insight.Intake.adx_portalcomment>("knowledgebaserecord_adx_portalcomments", null, value);
				this.OnPropertyChanged("knowledgebaserecord_adx_portalcomments");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Annotations")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Annotation> KnowledgeBaseRecord_Annotations
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Annotation>("KnowledgeBaseRecord_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Annotations");
				this.SetRelatedEntities<Insight.Intake.Annotation>("KnowledgeBaseRecord_Annotations", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Appointments")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Appointment> KnowledgeBaseRecord_Appointments
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Appointment>("KnowledgeBaseRecord_Appointments", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Appointments");
				this.SetRelatedEntities<Insight.Intake.Appointment>("KnowledgeBaseRecord_Appointments", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.AsyncOperation> KnowledgeBaseRecord_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.AsyncOperation>("KnowledgeBaseRecord_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_AsyncOperations");
				this.SetRelatedEntities<Insight.Intake.AsyncOperation>("KnowledgeBaseRecord_AsyncOperations", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> KnowledgeBaseRecord_DuplicateBaseRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("KnowledgeBaseRecord_DuplicateBaseRecord", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_DuplicateBaseRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("KnowledgeBaseRecord_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.DuplicateRecord> KnowledgeBaseRecord_DuplicateMatchingRecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.DuplicateRecord>("KnowledgeBaseRecord_DuplicateMatchingRecord", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_DuplicateMatchingRecord");
				this.SetRelatedEntities<Insight.Intake.DuplicateRecord>("KnowledgeBaseRecord_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Emails")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Email> KnowledgeBaseRecord_Emails
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Email>("KnowledgeBaseRecord_Emails", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Emails");
				this.SetRelatedEntities<Insight.Intake.Email>("KnowledgeBaseRecord_Emails", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Emails");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Faxes")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Fax> KnowledgeBaseRecord_Faxes
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Fax>("KnowledgeBaseRecord_Faxes", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Faxes");
				this.SetRelatedEntities<Insight.Intake.Fax>("KnowledgeBaseRecord_Faxes", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_IncidentResolutions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_IncidentResolutions")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.IncidentResolution> knowledgebaserecord_IncidentResolutions
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.IncidentResolution>("knowledgebaserecord_IncidentResolutions", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_IncidentResolutions");
				this.SetRelatedEntities<Insight.Intake.IncidentResolution>("knowledgebaserecord_IncidentResolutions", null, value);
				this.OnPropertyChanged("knowledgebaserecord_IncidentResolutions");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_ipg_carrier_audit_histories
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_ipg_carrier_audit_histories")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_carrier_audit_history> knowledgebaserecord_ipg_carrier_audit_histories
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_carrier_audit_history>("knowledgebaserecord_ipg_carrier_audit_histories", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_ipg_carrier_audit_histories");
				this.SetRelatedEntities<Insight.Intake.ipg_carrier_audit_history>("knowledgebaserecord_ipg_carrier_audit_histories", null, value);
				this.OnPropertyChanged("knowledgebaserecord_ipg_carrier_audit_histories");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_ipg_gateactivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_ipg_gateactivities")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_gateactivity> knowledgebaserecord_ipg_gateactivities
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_gateactivity>("knowledgebaserecord_ipg_gateactivities", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_ipg_gateactivities");
				this.SetRelatedEntities<Insight.Intake.ipg_gateactivity>("knowledgebaserecord_ipg_gateactivities", null, value);
				this.OnPropertyChanged("knowledgebaserecord_ipg_gateactivities");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_ipg_historicaudits
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_ipg_historicaudits")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ipg_historicaudit> knowledgebaserecord_ipg_historicaudits
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ipg_historicaudit>("knowledgebaserecord_ipg_historicaudits", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_ipg_historicaudits");
				this.SetRelatedEntities<Insight.Intake.ipg_historicaudit>("knowledgebaserecord_ipg_historicaudits", null, value);
				this.OnPropertyChanged("knowledgebaserecord_ipg_historicaudits");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Letters")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Letter> KnowledgeBaseRecord_Letters
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Letter>("KnowledgeBaseRecord_Letters", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Letters");
				this.SetRelatedEntities<Insight.Intake.Letter>("KnowledgeBaseRecord_Letters", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Letters");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_OrderCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_OrderCloses")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.OrderClose> knowledgebaserecord_OrderCloses
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.OrderClose>("knowledgebaserecord_OrderCloses", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_OrderCloses");
				this.SetRelatedEntities<Insight.Intake.OrderClose>("knowledgebaserecord_OrderCloses", null, value);
				this.OnPropertyChanged("knowledgebaserecord_OrderCloses");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.PhoneCall> KnowledgeBaseRecord_PhoneCalls
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.PhoneCall>("KnowledgeBaseRecord_PhoneCalls", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_PhoneCalls");
				this.SetRelatedEntities<Insight.Intake.PhoneCall>("KnowledgeBaseRecord_PhoneCalls", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_PrincipalObjectAttributeAccess
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_PrincipalObjectAttributeAccess")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.PrincipalObjectAttributeAccess> KnowledgeBaseRecord_PrincipalObjectAttributeAccess
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("KnowledgeBaseRecord_PrincipalObjectAttributeAccess", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_PrincipalObjectAttributeAccess");
				this.SetRelatedEntities<Insight.Intake.PrincipalObjectAttributeAccess>("KnowledgeBaseRecord_PrincipalObjectAttributeAccess", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_PrincipalObjectAttributeAccess");
			}
		}
		
		/// <summary>
		/// 1:N knowledgebaserecord_QuoteCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgebaserecord_QuoteCloses")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.QuoteClose> knowledgebaserecord_QuoteCloses
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.QuoteClose>("knowledgebaserecord_QuoteCloses", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgebaserecord_QuoteCloses");
				this.SetRelatedEntities<Insight.Intake.QuoteClose>("knowledgebaserecord_QuoteCloses", null, value);
				this.OnPropertyChanged("knowledgebaserecord_QuoteCloses");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.RecurringAppointmentMaster> KnowledgeBaseRecord_RecurringAppointmentMasters
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.RecurringAppointmentMaster>("KnowledgeBaseRecord_RecurringAppointmentMasters", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_RecurringAppointmentMasters");
				this.SetRelatedEntities<Insight.Intake.RecurringAppointmentMaster>("KnowledgeBaseRecord_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.ServiceAppointment> KnowledgeBaseRecord_ServiceAppointments
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.ServiceAppointment>("KnowledgeBaseRecord_ServiceAppointments", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_ServiceAppointments");
				this.SetRelatedEntities<Insight.Intake.ServiceAppointment>("KnowledgeBaseRecord_ServiceAppointments", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N KnowledgeBaseRecord_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Tasks")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Task> KnowledgeBaseRecord_Tasks
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Task>("KnowledgeBaseRecord_Tasks", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Tasks");
				this.SetRelatedEntities<Insight.Intake.Task>("KnowledgeBaseRecord_Tasks", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Tasks");
			}
		}
		
		/// <summary>
		/// N:N knowledgearticle_knowledgebaserecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_knowledgebaserecord")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.KnowledgeArticle> knowledgearticle_knowledgebaserecord
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.KnowledgeArticle>("knowledgearticle_knowledgebaserecord", null);
			}
			set
			{
				this.OnPropertyChanging("knowledgearticle_knowledgebaserecord");
				this.SetRelatedEntities<Insight.Intake.KnowledgeArticle>("knowledgearticle_knowledgebaserecord", null, value);
				this.OnPropertyChanged("knowledgearticle_knowledgebaserecord");
			}
		}
		
		/// <summary>
		/// N:N KnowledgeBaseRecord_Incident
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Incident")]
		public System.Collections.Generic.IEnumerable<Insight.Intake.Incident> KnowledgeBaseRecord_Incident
		{
			get
			{
				return this.GetRelatedEntities<Insight.Intake.Incident>("KnowledgeBaseRecord_Incident", null);
			}
			set
			{
				this.OnPropertyChanging("KnowledgeBaseRecord_Incident");
				this.SetRelatedEntities<Insight.Intake.Incident>("KnowledgeBaseRecord_Incident", null, value);
				this.OnPropertyChanged("KnowledgeBaseRecord_Incident");
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_createdby")]
		public Insight.Intake.SystemUser lk_KnowledgeBaseRecord_createdby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_KnowledgeBaseRecord_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_createdonbehalfby")]
		public Insight.Intake.SystemUser lk_KnowledgeBaseRecord_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_KnowledgeBaseRecord_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_KnowledgeBaseRecord_createdonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_KnowledgeBaseRecord_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_KnowledgeBaseRecord_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_modifiedby")]
		public Insight.Intake.SystemUser lk_KnowledgeBaseRecord_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_KnowledgeBaseRecord_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_KnowledgeBaseRecord_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_KnowledgeBaseRecord_modifiedonbehalfby")]
		public Insight.Intake.SystemUser lk_KnowledgeBaseRecord_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.SystemUser>("lk_KnowledgeBaseRecord_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_KnowledgeBaseRecord_modifiedonbehalfby");
				this.SetRelatedEntity<Insight.Intake.SystemUser>("lk_KnowledgeBaseRecord_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_KnowledgeBaseRecord_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_KnowledgeBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_KnowledgeBaseRecord")]
		public Insight.Intake.TransactionCurrency TransactionCurrency_KnowledgeBaseRecord
		{
			get
			{
				return this.GetRelatedEntity<Insight.Intake.TransactionCurrency>("TransactionCurrency_KnowledgeBaseRecord", null);
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrency_KnowledgeBaseRecord");
				this.SetRelatedEntity<Insight.Intake.TransactionCurrency>("TransactionCurrency_KnowledgeBaseRecord", null, value);
				this.OnPropertyChanged("TransactionCurrency_KnowledgeBaseRecord");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public KnowledgeBaseRecord(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["knowledgebaserecordid"] = base.Id;
                        break;
                    case "knowledgebaserecordid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}